### PR TITLE
docs: Update current status

### PR DESCRIPTION
**Pull request by max-sixty**
What does everyone think of this? I'm trying to balance brevity with completeness; excitement with prudence

### CODE REVIEW

**Comment by richb-hanover** [comment]
I like it - the tone, the tense you've used... Two comments:

- Consider adding a date - perhaps `## Current Status - October 2022` to the header. It helps readers understand how "live" the project is.
- Consider adding a link to the [Roadmap](https://prql-lang.org/roadmap/) page and check it over to see if there's anything else you want to add

Thanks!

**Review by aljazerzen — APPROVED** [review]
Sounds great.

**Comment by max-sixty** [comment]
Perfect @richb-hanover

**Comment by richb-hanover** [comment]
Looks good to me! Thanks

**Pull request merged**
