### PR TITLE
feat: Add option to output colors

### PR DESCRIPTION
**Pull request by max-sixty**
This moves #1355 forward, and enables a PR to add colors to the book. The main thing to review is whether the proposed structure and naming of the options is reasonable.

~On the names — it's not that consistent — we have `signature_comment` — should this just be `colors` rather than `use_colors`? Or does `signature_comment` suggest it contains an actual comment? I've generally tried to make bools self-describing, but possible an options struct can be more implicit.~ 

Edit: this is now just a `color` property and `.with_color(self, color)` method, consistent with something like https://github.com/zesterer/ariadne/blob/ccd465160129d2546d67f7ee78727a4098a64330/src/lib.rs#L81. Possibly we should standardize around something like that

---

It's slightly different from the proposal in #1355  — it doesn't introduce another layer of options.
- I think possibly the code has changed slightly since then, since there was a discussion on whether to pass an `Options` struct to the `compile` function, which we now already do. 
- And I would vote to lean towards having a flatter, simpler, structure until we have lots of confidence in the eventual structure. 
  - (Separate point, ref #1840 — possibly that would have also made the initial contribution easier, which was well-described in #1355 but was a decent amount of work? Possibly we should be trying to make the initial contributions as tiny as possible, even at the cost of them requiring later refactorings?)

---

I'm not completely clear how we support colors in `prqlc` now...
- We're currently [passing `false` to the `composed` method](https://github.com/PRQL/prql/compare/main...max-sixty:prql:colors?expand=1#diff-d8cf470395314450935c363c0f82ef23888873d109e7df81e131728c66265e84L128-R128), which is passed through to ariadne [here](https://github.com/PRQL/prql/blob/107f3d71a56805c59fa217090d3d213a50711f8b/prql-compiler/src/error.rs#L246)
- But we are getting colors! 
  image
- Possibly some combination of [Ariadne's features](https://github.com/zesterer/ariadne#cargo-features) and our [`color_eyre::install` usage](https://github.com/PRQL/prql/blob/79e5529413fecc66b824d1936e89ac3889f248fb/prql-compiler/prqlc/src/cli.rs#L20) auto configures it?
  - Though then how would we implement #1355 if passing `false` doesn't pass through to ariadne?

---

This doesn't implement support in bindings yet.

### CODE REVIEW

**Comment by max-sixty** [comment]
@aljazerzen given you're quasi-out for two weeks, give this a thumbs-down if you want me to wait — e.g. the options aren't named well — otherwise I'll merge. (better to wait than revert)

**Comment by eitsupi** [comment]
Could it be listed in the Changelog? (Downstream packages also need to add the new field to Options)

**Comment by max-sixty** [comment]
> Could it be listed in the Changelog? (Downstream packages also need to add the new field to Options)

Definitely, will do

More generally, if there's some check we could add — e.g. anything with a `fix` or `feat` requires an edit to the Changelog file, then I'd support that. (But I'm less keen on a separate tool like changie, I find that adds overhead to tiny PRs)

**Review by aljazerzen — APPROVED** [review]

**Comment by max-sixty** [comment]
> I'm not completely clear how we support colors in `prqlc` now...

FYI this was resolved in #2267

**Pull request merged**
