### PR TITLE
docs: Fix Playground sidebar

### PR DESCRIPTION
**Pull request by richb-hanover**
Fix disclosure ("twisty") triangles in Playground
Make section headings larger to match file names
Use white right-facing triangle - U+25b7 
Make the triangle a little smaller than the text
Put a non-breaking space in front of "fileRow" to indent them 
Wrap the PRQL website and Book links in a .fileRow div to indent them

### CODE REVIEW

**Comment by eitsupi** [comment]
I think there was a discussion somewhere earlier, but I am wondering if the links to the website and book in the sidebar can be removed (playground is now integrated with the navbar which has links).

image

**Comment by richb-hanover** [comment]
Those links wouldn't be available in the Dev Container, but that probably doesn't matter: anyone who's devoted enough to run the Dev Container can figure out how to open another browser tab...

**Comment by max-sixty** [comment]
> I think there was a discussion somewhere earlier, but I am wondering if the links to the website and book in the sidebar can be removed (playground is now integrated with the navbar which has links).

Agree on removing!

**Comment by max-sixty** [comment]
@richb-hanover thank you! Very nice result, very nice comments in the code!

**Pull request merged**
