### PR TITLE
docs: Update current status

### PR DESCRIPTION
**Pull request by max-sixty**
No substantial changes...

### CODE REVIEW

**Comment by snth** [comment]
OT comment: It always amuses me when people comment on seasons. For example when I scanned the changes in this PR and I saw "this summer" I thought "oh cool, have we got something planned for December?" and then when my eyes caught up reading the other changes I saw that you referred to the 0.9 release which already happened. Given the dominance of the northern hemisphere this makes sense but for those of us in the global south it is sometimes a bit of a jarring experience.

**Comment by max-sixty** [comment]
Haha! I think this debate / meme on Twitter for a while last year.

You're right though! Let's change it...

**Comment by max-sixty** [comment]
Fixed in #3557

**Comment by snth** [comment]
Thanks!

**Pull request merged**
