### PR TITLE
build: git ignore `target/`

### PR DESCRIPTION
**Pull request by eitsupi**
Revert the change made by #1600

### CODE REVIEW

**Comment by max-sixty** [comment]
The existing state was useful for me because I use `target_ra` for rust analyzer's build, so it doesn't conflict with the other version. Is there a path that starts with `target` that we want to include?

**Review by max-sixty — COMMENTED** [review]
The existing state was useful for me because I use target_ra for rust analyzer's build, so it doesn't conflict with the other version. Is there a path that starts with target that we want to include?

**Comment by eitsupi** [comment]
> The existing state was useful for me because I use target_ra for rust analyzer's build, so it doesn't conflict with the other version. Is there a path that starts with target that we want to include?

I noticed that the target directory was not grayed out on VS Code's explorer.
There are no directories I want to include. Since #1600 said "This will be fixed in an upcoming version of rustup though.", I assumed that this is no longer needed, but if you need it, please close this PR.

**Comment by max-sixty** [comment]
> Since #1600 said "This will be fixed in an upcoming version of rustup though.",

Ah OK, let's try this, then!

**Pull request merged**
