### PR TITLE
feat: Add hex escape

### PR DESCRIPTION
**Pull request by vanillajonathan**
Add hex escape inside strings such as `"Hello \x61"`.

### CODE REVIEW

**Comment by max-sixty** [comment]
Great to see you're working on the rust code @vanillajonathan ! Nice work.

Could we add a test for this? You can copy one from just below here: https://github.com/PRQL/prql/blob/ee71cd787e21d2d9a77cc9f10dd0d75df8f74bd5/crates/prql-parser/src/lexer.rs#L475. Lmk if you need any guidance...

**Comment by vanillajonathan** [comment]
Thanks!

I have added a test now.

**Comment by max-sixty** [comment]
Excellent! Congrats on a nice rust PR...

**Comment by vanillajonathan** [comment]
Thanks!

**Pull request merged**
