### PR TITLE
test: use `allow_duplicates` in integration test

### PR DESCRIPTION
**Pull request by max-sixty**
At risk of over-refining this file, this delegates the repeated checking of snapshots to insta

### CODE REVIEW

**Comment by aljazerzen** [comment]
I don't like this, because a comparison failure is not showing which two dialects are different from each other:

```

---- test_rdbms stdout ----
Snapshots in allow-duplicates block do not match.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Differences in Block ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: prql-compiler/tests/integration/snapshots/integration__results@window.prql.snap
Snapshot: results@window.prql
Source: prql-compiler/tests/integration/main.rs:347
Input file: prql-compiler/tests/integration/queries/window.prql
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-previous assertion
+current assertion
────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────
    0     0 │ 3379,23,1,40,3379
          1 │+3384,23,2,40,3384
          2 │+3399,23,3,40,3399
          3 │+3395,23,4,40,3395
          4 │+3377,23,5,40,3377
          5 │+3478,23,6,40,3478
          6 │+3385,23,7,40,3385
          7 │+3390,23,8,40,3390
          8 │+3381,23,9,40,3381
          9 │+3393,23,10,40,3393
    1    10 │ 3496,24,1,74,3496
         11 │+3501,24,2,74,3501
         12 │+3448,24,3,74,3448
         13 │+3452,24,4,74,3452
         14 │+3483,24,5,74,3483
         15 │+3449,24,6,74,3449
         16 │+3408,24,7,74,3408
         17 │+3447,24,8,74,3447
         18 │+3492,24,9,74,3492
         19 │+3500,24,10,74,3500
    2    20 │ 3451,25,1,1,3451
────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────
thread 'test_rdbms' panicked at 'snapshot assertion for 'results@window.prql' failed in line 347. Result does not match previous snapshot in allow-duplicates block.', /home/aljaz/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.30.0/src/runtime.rs:590:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'll revert.

**Comment by aljazerzen** [comment]
Also rust-analizer is not working in the macros. That's acceptable in small macros, but quite annoying here.

**Comment by aljazerzen** [comment]
Scratch that, rust-analizer is not working because this requires a feature now.

**Comment by max-sixty** [comment]
> I don't like this, because a comparison failure is not showing which two dialects are different from each other:

Hmmm, this was supposed to handle that: https://github.com/PRQL/prql/pull/2859/files#diff-61c6edc4c83a1ee02e8c718cd4c3fe7957d91b357a60b89daed30876c1544b3bR343-R346

But your message indeed suggests that it's not working...

**Pull request merged**
