### PR TITLE
docs: Fix operators table

### PR DESCRIPTION
**Pull request by richb-hanover**
Fixed table for the operator precedence in Operators.md

### CODE REVIEW

**Comment by max-sixty** [comment]
pow is part of https://github.com/PRQL/prql/pull/4125 !

Will merge tomorrow unless I get feedback.

Thank you for spotting though!

**Comment by max-sixty** [comment]
Will close since #4125 is merged. Thank you regardless!

**Comment by richb-hanover** [comment]
@max-sixty I'm not sure of the state of this, but the table of Operator Precedence (https://prql-lang.org/book/reference/syntax/operators.html#operator-precedence) in the public Book is still messed up. Would you check? Thanks

**Comment by max-sixty** [comment]
Yes, we should do a release. (Generally we push docs-only changes to `web`, but here it was both docs and code...)

In retrospect I should have merged yours, backported to web, and then resolved the conflicts with mine. Sorry!

**Comment by richb-hanover** [comment]
Ahah! I see now... Both code and docs. I shoulda made separate PRs. I'll do that next time... Thanks

**Comment by max-sixty** [comment]
> Ahah! I see now... Both code and docs. I shoulda made separate PRs. I'll do that next time... Thanks

Yours was perfect! Because this was docs only. So mea culpa...

**Comment by richb-hanover** [comment]
I don't do "blame". It's enough if it gets fixed when it's pointed out. See [WPNTFIIWDKIB](https://randomneuronsfiring.com/wpntfiiwdkib/)

**Pull request closed without merging**
