### PR TITLE
devops: Don't change user for devcontainer

### PR DESCRIPTION
**Pull request by max-sixty**
From #3709

### CODE REVIEW

**Comment by eitsupi** [comment]
What does this change mean?
There is no point in this in my understanding.

**Comment by max-sixty** [comment]
If we build as `root`, and then connect as `root` — would that plausibly prevent the error in #3709? I'm not confident here at all...

...but we also have multiple users in our image, and they're not working together well on Mac, and it seems unlikely to be a bug with VS Code. So hence the attempt to simplify...

**Comment by eitsupi** [comment]
Please read the official documentation.
Which users are used in the container is recorded in the metadata (Docker image label) and is set upstream.
It is not related to this repository.
Overwriting with the root user completely destroys the operation on the Linux file system including WSL2 (unless you want it)

I don't understand at all why you would change the file here and ask me for a review without following my advice and opening the issue upstream

**Comment by max-sixty** [comment]
> I don't understand at all why you would change the file here and ask me for a review without following my advice and opening the issue upstream

Can you help me understand why this is an upstream issue? I'm all for logging issues where they belong. But are

**Pull request closed without merging**
