### PR TITLE
docs: Update CHANGELOG.md to link to updated `switch` example

### PR DESCRIPTION
**Pull request by richb-hanover**
I was surprised to see the `=>` syntax described as 0.5.0, yet have it implemented in the current Playground.

I would suggest that we use the "0.x.y - Unreleased" section to contain _everything_ that is currently implemented, even if it arrives prior to its "stated delivery date/release" in the Roadmap.

### CODE REVIEW

**Comment by snth** [comment]
I agree with you and just commented on this in #1581.

While I'm very much for the change, we need to figure something out about the release process and website updates.

**Comment by max-sixty** [comment]
I think we can add a section to the template with `**Breaking changes**`, WDYT?

**Comment by TaxFairness** [comment]
> I think we can add a section to the template with `**Breaking changes**`, WDYT?

I have seen the separate "Breaking Changes" section, but I have a sense that we should keep all the "features" (new or altered) together. They're what most people want/need to see. 

As I look at the 0.3.0 CHANGELOG entries, I would have placed all seven (three breaking, four new) items in the same group so they're seen as the "Big News" part of the release. All the rest of the 0.3.0 entries are careful reporting of other stuff that happened.  By marking each of those three as **Breaking change**, that information stays with the feature description (and won't get lost if items get re-ordered).

**Comment by richb-hanover** [comment]
Uh oh... @TaxFairness (my alter-ego) responded. It was really me :-)

**Comment by max-sixty** [comment]
> Uh oh... @TaxFairness (my alter-ego) responded. It was really me :-)

I agree with your alter ego!

**Comment by aljazerzen** [comment]
This change was placed in 0.5.0 section because it is a breaking change, which cannot go into a patch release.

The fact that playground & book immediately contained the change is a separate problem from #1507

**Comment by aljazerzen** [comment]
Disregard that: semver states that "Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable."

**Comment by TaxFairness** [comment]
I'm glad to hear a citation for the rule (which makes complete sense). Thanks.

**Comment by aljazerzen** [comment]
Since the breaking change has been reverted, I removed the entry in the changelog, but kept the extended entry about `from_text`.

Thanks for contributing.

**Comment by max-sixty** [comment]
Good changes, thank you!

**Pull request merged**
