### PR TITLE
feat: Add function to python binding with JSON error

### PR DESCRIPTION
**Pull request by max-sixty**
This does the very basic version of #4061.

I tried to do the advanced version of https://github.com/PRQL/prql/issues/4061, where we add an attribute onto the exception, but couldn't manage. I think we need to wait for the next version of PyO3, where https://github.com/PyO3/pyo3/pull/3475 will work (using that exact code generates errors in 0.20.2)

### CODE REVIEW

**Comment by eitsupi** [comment]
Why not use such functionality in `prql_to_pl`, `pl_to_rq`, and `rq_to_sql` instead of adding a new function `prql_to_sql`?
It seems logical to me that functions that provide a lower level API would provide more detailed errors.
(I think JS bindings can be updated in the same way)

**Comment by max-sixty** [comment]
> Why not use such functionality in `prql_to_pl`, `pl_to_rq`, and `rq_to_sql` instead of adding a new function `prql_to_sql`? It seems logical to me that functions that provide a lower level API would provide more detailed errors. (I think JS bindings can be updated in the same way)

Yes, this is a good point! I think that would have been a better approach.

I think fairly soon we can just have an exception that has the full errors at attributes, rather than two different types of exception. Basically when we get the next PyO3 version.

Unless you feel strongly, I won't revert this — it labelled as being temporary, and it does seem marginally useful...

**Comment by max-sixty** [comment]
Actually on further reflection, maybe this is worse and we should revert? And instead just suggest that folks use something like:

```python
try:
  x = prql_to_pl(query)
  x = pl_to_rq(x)
  x = rq_to_sql(x)
except Exception as e:
  json_exception = e
```

WDYT @eitsupi (/ others)?

**Comment by eitsupi** [comment]
I feel it would be better to revert it for the following reasons:

1. Function name doesn't say what it does. (The name `prql_to_sql` does not indicate the nature of the error being a json.)
2. I think it's quite difficult to understand that there are multiple functions that do almost the same thing.

**Comment by max-sixty** [comment]
OK agree, thanks @eitsupi . 

Reverted in #4074, and we can do the good thing after PyO3 is released

**Pull request merged**
