### PR TITLE
fix: the range_of_ranges should check the Range end is smaller than its start

### PR DESCRIPTION
**Pull request by Shuozeli**
Fix the issue described in [issue/945](https://github.com/prql/prql/issues/945).

### CODE REVIEW

**Comment by max-sixty** [comment]
Perfect code! 

If you want to add to the changelog then great, otherwise I'll do it in the release.

**Comment by Shuozeli** [comment]
> Perfect code!
> 
> If you want to add to the changeling then great, otherwise I'll do it in the release.

Could you share the changeling file you referred to? I couldn't find the instruction for updating the changeling in the contributing doc.

**Comment by max-sixty** [comment]
Sorry, this was an autocorrect! The file is `CHANGELOG.md`

**Comment by Shuozeli** [comment]
> Sorry, this was an autocorrect! The file is `CHANGELOG.md`

Done

**Comment by max-sixty** [comment]
Thank you v much @Shuozeli !

**Pull request merged**
