### PR TITLE
test: combine prql-compiler test binaries, test_each_file

### PR DESCRIPTION
**Pull request by aljazerzen**
Followup for #3715

This PR does two things:
- combines `prqlc/prql-compiler/tests/integration` and `prqlc/prql-compiler/tests/sql` into a single test binary,
- replaces `insta::glob!` with `test_each_file::test_each_path!`, which is a macro that generates separate tests:

```
prql-compiler::integration:
    bad_error_messages::array_instead_of_tuple
    bad_error_messages::empty_interpolations
...
    error_messages::test_ambiguous
    error_messages::test_ambiguous_inference
...
    parser::check_invalid_version
    parser::check_valid_version
...
    queries::compile::aggregation   <-- all of these used to be a single test
    queries::compile::arithmetic   
    queries::compile::cast
    queries::compile::constants_only
    queries::compile::distinct
    queries::compile::distinct_on
    queries::compile::genre_counts
    queries::compile::group_all
    queries::compile::group_sort
    queries::compile::invoice_totals
    queries::compile::loop_01
    queries::compile::pipelines
    queries::compile::read_csv
    queries::compile::set_ops_remove
    queries::compile::sort
    queries::compile::switch
    queries::compile::window
    queries::fmt::aggregation
    queries::fmt::arithmetic
    queries::fmt::cast
    queries::fmt::constants_only
    queries::fmt::distinct
    queries::fmt::distinct_on
    queries::fmt::genre_counts
    queries::fmt::group_all
    queries::fmt::group_sort
    queries::fmt::invoice_to
...
```

This means that when a test panics:
- it is easy to see which test file panicked,
- other tests will run regardless.

I've also started using `cargo-nextest`, which has nicer printout and cuts run time of all tests from 7.5sec to 4.8sec. Not much, but it's something.

### CODE REVIEW

**Comment by max-sixty** [comment]
> replaces `insta::glob!` with `test_each_file::test_each_path!`, which is a macro that generates separate tests:

Yeah, it's a shame that `glob!` doesn't show enough detail; I agree it's annoying when the test doesn't immediately & obviously show what's wrong. FWIW I think it used to — I wouldn't have switched that back unless I had thought it did, with the `description` field etc. 

I put https://github.com/mitsuhiko/insta/issues/424 in, but haven't got to even starting on it.

So +1 for the change given our constraints, thanks...

**Review by max-sixty — APPROVED** [review]

**Comment by aljazerzen** [comment]
Making `glob!` report more details would be hard. That's because when a test panics, you would have to catch that panic, recover, print the panic message and continue with other tests.

This same logic is already implemented by the Rust's `#[test]` macro (or some other internal machinery), so `test_each_file!` takes advantage of that:

```Rust
test_each_path! { in "./prqlc/prql-compiler/tests/integration/queries" as compile => run }

fn run(prql_path: &Path) {
    ...
}
```
... will expand to:
```rust
mod compile {
    #[test]
    fn arithmentic() {
        run(PathBuf::new("./prqlc/prql-compiler/tests/integration/queries/arithmentic.prql));
    }

    #[test]
    fn group() {
        run(PathBuf::new("./prqlc/prql-compiler/tests/integration/queries/group.prql));
    }

    ...
}
```

**Comment by aljazerzen** [comment]
I wish I could change all tests to `test_each_path!`, but the db tests require a shared state for the database. I might do something along the lines of this: https://stackoverflow.com/questions/41551036/sharing-dynamic-state-between-tests

**Comment by max-sixty** [comment]
> Making glob! report more details would be hard. That's because when a test panics, you would have to catch that panic, recover, print the panic message and continue with other tests.

Is this different to the other tests though? Insta achieves this for non-glob tests, I think?

I can look more. IIUC it uses CARGO_FORCE_PASS. And because it has its own macro, it can avoid panicking until the end...

**Comment by aljazerzen** [comment]
> Is this different to the other tests though? Insta achieves this for non-glob tests, I think?

It does not, I think. That's why I was splitting the tests. It just doesn't panic on non-matching snapshots.

> it has its own macro, it can avoid panicking until the end...

Macros are just a fancy way to write plain Rust code. You can see what do the macros expand to with `cargo expand --test=integration queries`

**Comment by max-sixty** [comment]
> It just doesn't panic on non-matching snapshots.

It doesn't panic per se, but it does exit with a non-zero exit code.

And with `--check` (which is default in CI), it shows the full output rather than proposing a snapshot change:

```
cargo insta test -p prqlc-parser --check
    Blocking waiting for file lock on build directory
    Finished test [unoptimized + debuginfo] target(s) in 2.45s
     Running unittests src/lib.rs (target/debug/deps/prqlc_parser-653f00769a9839a4)

running 4 tests
test lexer::numbers ... ok
test interpolation::parse_interpolate ... ok
test lexer::test_line_wrap ... ok
test lexer::quotes ... FAILED

failures:

---- lexer::quotes stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: quotes
Source: prqlc/prqlc-parser/src/lexer.rs:601
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: quoted_string(false).parse(r#"'aou'"#).unwrap()
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    0       │-aoeu
          0 │+aou
────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'lexer::quotes' panicked at 'snapshot assertion for 'quotes' failed in line 601', /Users/maximilian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.34.0/src/runtime.rs:563:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    lexer::quotes

test result: FAILED. 3 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.06s

error: test failed, to rerun pass `-p prqlc-parser --lib`
error: 1 target failed:
    `-p prqlc-parser --lib`
info: no snapshots to review
```

**Comment by max-sixty** [comment]
OK and surprisingly I _am_ also seeing this in `glob!`; i.e. with this diff:

```diff
diff --git a/prqlc/prql-compiler/tests/integration/queries.rs b/prqlc/prql-compiler/tests/integration/queries.rs
index 600628fe..89519b3e 100644
--- a/prqlc/prql-compiler/tests/integration/queries.rs
+++ b/prqlc/prql-compiler/tests/integration/queries.rs
@@ -122,7 +122,7 @@ fn test_queries_dbs() {
             insta::with_settings!({
                 description=>format!("# Running on dialect `{}`\n\n# Query:\n---\n{}", &con.dialect, &prql)
             }, {
-                assert_snapshot!("results", &result, &prql);
+                assert_snapshot!("results", "aoue", &prql);
             })
         }
         }
diff --git a/prqlc/prqlc-parser/src/lexer.rs b/prqlc/prqlc-parser/src/lexer.rs
index 17554a82..b6cd7bfa 100644
--- a/prqlc/prqlc-parser/src/lexer.rs
+++ b/prqlc/prqlc-parser/src/lexer.rs
@@ -598,7 +598,7 @@ fn quotes() {
     use insta::assert_snapshot;
 
     // All these are valid & equal.
-    assert_snapshot!(quoted_string(false).parse(r#"'aoeu'"#).unwrap(), @"aoeu");
+    assert_snapshot!(quoted_string(false).parse(r#"'aou'"#).unwrap(), @"aoeu");
     assert_snapshot!(quoted_string(false).parse(r#"'''aoeu'''"#).unwrap(), @"aoeu");
     assert_snapshot!(quoted_string(false).parse(r#"'''''aoeu'''''"#).unwrap(), @"aoeu");
     assert_snapshot!(quoted_string(false).parse(r#"'''''''aoeu'''''''"#).unwrap(), @"aoeu");
```

` cargo insta test -p=prql-compiler --features=test-dbs --check` does give the description

Note the `# Running on dialect duckdb`:

```

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: prqlc/prql-compiler/tests/integration/snapshots/integration__queries__results@group_sort.prql.snap
Snapshot: results@group_sort.prql
Source: prqlc/prql-compiler/tests/integration/queries.rs:125
Input file: prqlc/prql-compiler/tests/integration/queries/group_sort.prql
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: # mssql:test
from tracks
derive d = album_id + 1
group d (
    aggregate {
        n1 = (track_id | sum),
    }
)
sort d
take 10
select { d1 = d, n1 }

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# Running on dialect `duckdb`

# Query:
---
# mssql:test
from tracks
derive d = album_id + 1
group d (
    aggregate {
        n1 = (track_id | sum),
    }
)
sort d
take 10
select { d1 = d, n1 }
```

So https://github.com/mitsuhiko/insta/issues/424 needs to be more specific on the issue I was seeing.

If you remember — what was difficult about using `cargo insta` for these? That we didn't know what dialect was running?

**Comment by aljazerzen** [comment]
I'm not following. What have you discovered?

**Comment by max-sixty** [comment]
Sorry.

What was the disadvantage of insta, if you remember?

I had thought that using `insta::glob` didn't give enough context on what file & dialect was failing, since I saw that myself recently.

But then I tested that just now, and found that it _did_ show these details. But it sounds like you had issues too — do you remember what were your reasons for moving away from `insta::glob`?

**Comment by aljazerzen** [comment]
When we had a single `#[test]` that contained `glob!`, a panic would:
- not print which file or connection (dialect) caused the panic, :x:
- prevent all other files or connections from being tested, regardless of `--no-fail-fast` :x:

Non-matching snapshot error did contain info about which file caused the error. :white_check_mark: 

`with_duplicates!` error did **not** contain info about which dialect was not matching. :x:

**Comment by aljazerzen** [comment]
Now that we have one `#[test]` per query file, a panic would:
- print which file caused the panic :white_check_mark:, but not which connection (dialect)  :x:
- allow other files and connections to be tested with --no-fail-fast :white_check_mark: 

Non-matching snapshot error contains info about which file caused the error. :white_check_mark: 

`with_duplicates!` error does contain info about which dialect was not matching. :white_check_mark:

**Comment by max-sixty** [comment]
Perfect!

> `with_duplicates!` error did **not** contain info about which dialect was not matching. ❌

Thanks — this is what I was seeing, then.

> a panic would:
> 
>     * not print which file or connection (dialect) caused the panic, ❌

Ah, this is what you meant about panics — I see now. I was confusing the discussion for a panic caused by an assert vs. a panic from running our code.

**Comment by aljazerzen** [comment]
Yeah, it's hard to be specific here, since we have a bunch of tests, some containing multiple tests (assertions) and then a super test that runs a bunch of tests (for each file) and then tests other dialects :confounded:, each of which can panic, not match with a snapshot or not match with each other.

**Comment by max-sixty** [comment]
(I'm quite impressed you remember all the context of what works where!)

**Comment by aljazerzen** [comment]
I know what was pestering me before!

**Comment by aljazerzen** [comment]
I wouldn't be spending time on stuff that was not bothering me. Obviously! Never. \s

**Pull request merged**
