### PR TITLE
docs: Update `select` discussion of table / namespace

### PR DESCRIPTION
**Pull request by richb-hanover**
I wasn't quite sure I understood the explanation. Here's my attempt to explain it. Thanks.

### CODE REVIEW

**Comment by max-sixty** [comment]
Thanks @richb-hanover — unfortunately it seems like we might have done the same thing! Our explanations are fairly similar!

I did make an effort to tag the original issue in the PR, sorry if that wasn't visible enough.

Feel free to edit my explanation with anything you think can be improved!

**Comment by richb-hanover** [comment]
Hmmm... I was responding to the description that (I think) is still [in the Book](https://prql-lang.org/book/transforms/select.html#examples)

When I first read it, I didn't quite understand what was being said, and the examples didn't help me. I am experimenting with the language to make it more explicit about the thing that isn't available. (I will be glad for corrections if I've got it wrong.)

**Comment by richb-hanover** [comment]
I also realize I don't entirely understand how to connect the example PRQL code and the resulting SQL...

**Comment by max-sixty** [comment]
Did you see the PR at https://github.com/prql/prql/pull/1285? It was not merged when you wrote this PR (but was opened 6 hours earlier...). 

It's now merged, so that means we have some conflicts with your branch:
 
image

**Comment by richb-hanover** [comment]
@max-sixty  ~~No - I hadn't seen that. Let me read it over... Thanks.~~

Actually, I had seen it - here's my reasoning for the change...

- I wanted to be clear that the `e` represents the `employees` table
- I wanted to note that it's not so much an "alias issue", but that the `e` is just _gone_ after the `select`
- I wanted to use a `filter` statement in the example since it's kind of orthogonal to the use of `select`
- I switched to using `fname` as the variable name, because my brain initially saw `fn` as "function"
- I wanted to remind the user that the `fname` variable referred to the column
- I removed the apparent time-sensitive word "currently" - it makes it seem as if a (major?) change might be in the wings.

**Comment by max-sixty** [comment]
Very open to changes — do you want to merge the current version into yours, and then we can see the diff?

**Comment by richb-hanover** [comment]
Abandoned - merging (new) main branch into mine...

**Pull request closed without merging**
