### PR TITLE
Fix BigQuery quoting

### PR DESCRIPTION
**Pull request by max-sixty**
Not sure this will be the end of it, but progress

### CODE REVIEW

**Comment by max-sixty** [comment]
(I need to do some checks before merging, e.g. should the * be outside the backticks)

**Comment by max-sixty** [comment]
(Continuing on from https://github.com/prql/prql/issues/852)

It's actually a bit more complicated than this!

Because it's required to have the column name (or `*`) outside the quote:

```sql
SELECT
  `bigquery-public-data.pypi.file_downloads`.country_code
-- or  
--    `bigquery-public-data.pypi.file_downloads`.*
FROM
  `bigquery-public-data.pypi.file_downloads`
WHERE
  timestamp = '2021-08-01'
```

This is not valid:

```diff
SELECT
-  `bigquery-public-data.pypi.file_downloads`.country_code
+  `bigquery-public-data.pypi.file_downloads.country_code`
\--or
---    `bigquery-public-data.pypi.file_downloads`.*
+--    `bigquery-public-data.pypi.file_downloads.*`
```

But the rule of "leave the final ident outside of the quotes" doesn't work, because the whole table must be quoted in the `FROM` clause.

So we probably need to branch higher in the translator and operate differently for column vs. table names. 

Another option would be to have more semantic understanding of the identifier — e.g. whether something is a table vs a column name — in the translator. Probably longer term this has more general utility, but I'm not sure how far it is now; I'm getting more up to speed with `semantic`. (CC @aljazerzen !)

**Comment by max-sixty** [comment]
I don't think I made `translator.rs`'s code quality go up, but I _think_ it works now. Please reply to any bugs here! 

I'm also going to kick off a couple of issues — for BQ integration tests, and for our `translator.rs` architecture.

**Comment by blackary** [comment]
@max-sixty Thanks! It looks good from the playground. I'll let you know if I run into any more issues.

**Pull request merged**
