### PR TITLE
fix: Raise an error on an invalid header arg

### LINKED ISSUE #2230: Additional named args in header don't error
### What happened?

We don't raise an error on args in the header which aren't supported

### PRQL input

```elm
prql dialect:sql.duckdb  # This should be `target`, not `dialect`

from x
```

### SQL output

```SQL
SELECT
  *
FROM
  x

-- Generated by PRQL compiler version:0.6.1 (https://prql-lang.org)
```

### Expected SQL output

```SQL
Error, unknown arg `dialect`
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by max-sixty**

### CODE REVIEW

**Comment by max-sixty** [comment]
Would close https://github.com/PRQL/prql/issues/2230

But possibly there was a reason for this flexibility — I could imagine it being helpful? I think we should error _somewhere_ in the compilation — maybe the parser should be more flexible than the proposed code; but then let's error later.

**Comment by eitsupi** [comment]
Is there a test for when more than one header is set?
Something like the following

```elm
prql target:sql.mssql version:"0.6"

from a
take 5
```

**Comment by max-sixty** [comment]
Good idea @eitsupi — pushed

**Review by aljazerzen — APPROVED** [review]

**Comment by aljazerzen** [comment]
Nice, great idea to restrict headers. If we would not restrict them, adding any new header would be a breaking change, because before someone may have relied on the fact that they are ignored.

**Pull request merged**
