### PR TITLE
test: Add Stack-Overflowing query

### PR DESCRIPTION
**Pull request by max-sixty**
#2857

### CODE REVIEW

**Comment by max-sixty** [comment]
This is the longest query and seems to pass on Windows!

My guess is that the changes in https://github.com/PRQL/prql/pull/2878 did fix this — I can't be sure — but I think we can merge & close until we find a case that fails on the current `main` — is that reasonable?

**Comment by eitsupi** [comment]
Unfortunately, prqlc still seems to fail to compile.
I don't know why the test passes and prqlc fails.......

**Comment by max-sixty** [comment]
@eitsupi sorry to ask you so often to try things out. 

Can I ask — does the test pass on your system too? i.e. the query in the test fails when being piped to `cargo run -p prqlc -- compile -`, but the test itself passes?

We can add a `prqlc` test in that case...

**Comment by eitsupi** [comment]
First I need to start by installing Rust on Windows...... (I hope I simply run `winget install Rustlang.Rustup`)

**Comment by eitsupi** [comment]
@max-sixty Sorry, but I can't build libduckdb-sys, so I can't test it.
I don't know what the problem is as this is the first time I have installed Rust and MSVC tools on Windows......

(Since DuckDB is really hard to build, I am wondering if DuckDB can be removed from anything other than integration tests......)

```sh
❯ cargo-insta test --package prql-compiler
   Compiling libduckdb-sys v0.8.0
error: failed to run custom build command for `libduckdb-sys v0.8.0`

Caused by:
  process didn't exit successfully: `C:\Users\foo\Downloads\prql-main\target\debug\build\libduckdb-sys-4803c29a8b2379a3\build-script-build` (exit code: 1)
  --- stderr


  error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-I" "duckdb" "-I" "duckdb/third_party/fastpforlib" "-I" "duckdb/third_party/re2" "-I" "duckdb/third_party/fsst" "-I" "duckdb/third_party/jaro_winkler" "-I" "duckdb/src/include" "-I" "duckdb/third_party/utf8proc/include" "-I" "duckdb/third_party/concurrentqueue" "-I" "duckdb/third_party/utf8proc" "-I" "duckdb/third_party/httplib" "-I" "duckdb/third_party/mbedtls" "-I" "duckdb/third_party/tdigest" "-I" "duckdb/third_party/libpg_query/include" "-I" "duckdb/third_party/miniz" "-I" "duckdb/third_party/fmt/include" "-I" "duckdb/third_party/hyperloglog" "-I" "duckdb/third_party/mbedtls/library" "-I" "duckdb/third_party/libpg_query" "-I" "duckdb/third_party/pcg" "-I" "duckdb/third_party/fast_float" "-I" "duckdb/third_party/jaro_winkler/details" "-I" "duckdb/third_party/mbedtls/include" "/bigobj" "-DDUCKDB_BUILD_LIBRARY" "-FoC:\\Users\\foo\\Downloads\\prql-main\\target\\debug\\build\\libduckdb-sys-1e062f193d69ce5c\\out\\duckdb/ub_src_function_table_system.o" "-c" "duckdb/ub_src_function_table_system.cpp" with args "cl.exe" did not execute successfully (status code exit code: 2).
```

**Comment by max-sixty** [comment]
~Ah, so how have you been doing all this great rust code without building the project?? :)~ Edit: I guess you've been using the dev container!

Yes, we can put it behind a feature flag if needed. I hadn't known it was difficult to build on Windows — I guess the CI image has lots of setup already.

**Comment by eitsupi** [comment]
Thanks for updates!

I downloaded the latest version (d78dc0bbe2cb09b4b83663c777aa5f471847aa26) and the test was passed...

```sh
❯ cargo-insta test --package prql-compiler
   Compiling cfg-if v1.0.0
   Compiling memchr v2.5.0
   Compiling proc-macro2 v1.0.59
   Compiling autocfg v1.1.0
   Compiling quote v1.0.28
   Compiling unicode-ident v1.0.9
   Compiling serde v1.0.163
   Compiling cc v1.0.79
   Compiling windows_x86_64_msvc v0.48.0
   Compiling winapi v0.3.9
   Compiling libc v0.2.144
   Compiling crossbeam-utils v0.8.15
   Compiling version_check v0.9.4
   Compiling windows_x86_64_msvc v0.42.2
   Compiling once_cell v1.18.0
   Compiling ryu v1.0.13
   Compiling getrandom v0.2.9
   Compiling itoa v1.0.6
   Compiling log v0.4.17
   Compiling io-lifetimes v1.0.11
   Compiling anstyle v1.0.0
   Compiling either v1.8.1
   Compiling ahash v0.7.6
   Compiling memoffset v0.8.0
   Compiling crossbeam-epoch v0.9.14
   Compiling lazy_static v1.4.0
   Compiling regex-syntax v0.7.2
   Compiling rustversion v1.0.12
   Compiling serde_json v1.0.96
   Compiling windows-targets v0.48.0
   Compiling scopeguard v1.1.0
   Compiling windows-sys v0.48.0
   Compiling psm v0.1.21
   Compiling stacker v0.1.15
   Compiling backtrace v0.3.67
   Compiling windows-targets v0.42.2
   Compiling itertools v0.10.5
   Compiling indexmap v1.9.3
   Compiling num-traits v0.2.15
   Compiling heck v0.4.1
   Compiling gimli v0.27.2
   Compiling regex-automata v0.1.10
   Compiling hashbrown v0.12.3
   Compiling adler v1.0.2
   Compiling aho-corasick v1.0.1
   Compiling syn v2.0.17
   Compiling rayon-core v1.11.0
   Compiling miniz_oxide v0.6.2
   Compiling bstr v0.2.17
   Compiling object v0.30.3
   Compiling crossbeam-deque v0.8.3
   Compiling crossbeam-channel v0.5.8
   Compiling windows-sys v0.45.0
   Compiling num_cpus v1.15.0
   Compiling bitflags v1.3.2
   Compiling unicode-segmentation v1.10.1
   Compiling minimal-lexical v0.2.1
   Compiling utf8parse v0.2.1
   Compiling ciborium-io v0.2.1
   Compiling semver v1.0.17
   Compiling encode_unicode v0.3.6
   Compiling is-terminal v0.4.7
   Compiling clap_lex v0.5.0
   Compiling plotters-backend v0.3.4
   Compiling rustc-demangle v0.1.23
   Compiling half v1.8.2
   Compiling anyhow v1.0.71
   Compiling regex v1.8.3
   Compiling similar v2.2.1
   Compiling winapi-util v0.1.5
   Compiling plotters-svg v0.3.3
   Compiling same-file v1.0.6
   Compiling console v0.15.7
   Compiling walkdir v2.3.3
   Compiling ciborium-ll v0.2.1
   Compiling clap_builder v4.3.0
   Compiling nom v7.1.3
   Compiling anstyle-wincon v1.0.1
   Compiling addr2line v0.19.0
   Compiling anstyle-query v1.0.0
   Compiling anstyle-parse v0.2.0
   Compiling aho-corasick v0.7.20
   Compiling csv-core v0.1.10
   Compiling bstr v1.5.0
   Compiling yansi v0.5.1
   Compiling unicode-width v0.1.10
   Compiling fnv v1.0.7
   Compiling unsafe-libyaml v0.2.8
   Compiling colorchoice v1.0.0
   Compiling linked-hash-map v0.5.6
   Compiling unicode_categories v0.1.1
   Compiling cast v0.3.0
   Compiling anstream v0.3.2
   Compiling yaml-rust v0.4.5
   Compiling criterion-plot v0.5.0
   Compiling plotters v0.3.4
   Compiling globset v0.4.10
   Compiling sqlformat v0.2.1
   Compiling clap v4.3.0
   Compiling ariadne v0.3.0
   Compiling rayon v1.7.0
   Compiling chumsky v0.9.2
   Compiling anes v0.1.6
   Compiling oorandom v11.1.3
   Compiling similar-asserts v1.4.2
   Compiling serde_derive v1.0.163
   Compiling strum_macros v0.25.0
   Compiling enum-as-inner v0.6.0
   Compiling strum v0.25.0
   Compiling ciborium v0.2.1
   Compiling csv v1.2.1
   Compiling sqlparser v0.34.0
   Compiling serde_yaml v0.9.21
   Compiling insta v1.29.0
   Compiling tinytemplate v1.2.1
   Compiling criterion v0.5.1
   Compiling prql-compiler v0.8.1 (C:\Users\foo\Downloads\prql-main\prql-compiler)
    Finished test [unoptimized + debuginfo] target(s) in 1m 39s
     Running unittests src\lib.rs (target\debug\deps\prql_compiler-9d252e99e41f9ee0.exe)

running 188 tests
test ast::pl::ident::test_starts_with ... ok
test codegen::test::test_double_braces ... ok
test codegen::test::test_escaped_string ... ok
test codegen::test::test_simple ... ok
test codegen::test::test_range ... ok
test codegen::test::test_unary ... ok
test codegen::test::test_assign ... ok
test parser::test::test_case ... ok
test parser::test::test_assign ... ok
test parser::test::test_annotation ... ok
test parser::test::test_coalesce ... ok
test parser::test::test_allowed_idents ... ok
test parser::test::test_backticks ... ok
test parser::test::test_error_unexpected ... ok
test parser::test::test_array ... ok
test parser::test::test_derive ... ok
test codegen::test::test_pipeline ... ok
test parser::test::test_error_unicode_string ... ok
test parser::test::test_filter ... ok
test parser::test::test_dates ... ok
test parser::test::test_aggregate ... ok
test parser::test::test_expr ... ok
test parser::test::test_inline_pipeline ... ok
test parser::test::test_gt_lt_gte_lte ... ok
test parser::test::test_ident_with_keywords ... ok
test parser::test::test_func_call ... ok
test parser::test::test_literal ... ok
test parser::test::test_multiline_string ... ok
test parser::test::test_params ... ok
test parser::test::test_regex ... ok
test parser::test::test_s_string ... ok
test parser::test::test_s_string_braces ... ok
test parser::test::test_op_precedence ... ok
test parser::test::test_number ... ok
test parser::test::test_select ... ok
test parser::test::test_sql_parameters ... ok
test parser::test::test_unicode ... ok
test parser::test::test_basic_exprs ... ok
test parser::test::test_ranges ... ok
test parser::test::test_string ... ok
test parser::test::test_tab_characters ... ok
test parser::test::test_take ... ok
test parser::test::test_function ... ok
test parser::test::test_sort ... ok
test semantic::eval::test::basic ... ok
test semantic::module::tests::test_module ... ok
test semantic::module::tests::test_module_shadow_unshadow ... ok
test semantic::eval::test::pipelines ... ok
test parser::test::test_var_defs ... ok
test semantic::eval::test::tuples ... ok
test semantic::eval::test::columnar ... ok
test parser::test::test_tuple ... ok
test parser::test::test_pipeline_parse_tree ... ok
test parser::test::test_var_def ... ok
test semantic::test::check_invalid_version ... ok
test semantic::eval::test::transforms ... ok
test semantic::eval::test::window ... ok
test semantic::test::check_valid_version ... ok
test sql::dialect::tests::test_dialect_from_str ... ok
test sql::gen_expr::test::test_range_of_ranges ... ok
test sql::gen_expr::test::test_translate_datetime_literal_with_sqlite_function ... ok
test semantic::resolver::test::test_functions_1 ... ok
test semantic::resolver::test::test_non_existent_function ... ok
test semantic::test::test_resolve_01 ... ok
test semantic::resolver::test::test_functions_nested ... ok
test semantic::test::test_resolve_02 ... ok
test semantic::resolver::test::test_named_args ... ok
test semantic::test::test_resolve_03 ... ok
test tests::test::json_of_test ... ok
test semantic::test::test_resolve_04 ... ok
test semantic::resolver::test::test_variables_1 ... ok
test semantic::transforms::tests::test_transform_sort ... ok
test sql::test::test_end_with_new_line ... ok
test semantic::test::test_header ... ok
test semantic::resolver::test::test_functions_pipeline ... ok
test tests::test::test_1535 ... ok
test tests::test::test_basic_agg ... ok
test sql::gen_query::test::test_filter_windowed ... ok
test sql::gen_query::test::test_derive_filter ... ok
test sql::gen_query::test::test_variable_after_aggregate ... ok
test tests::test::large_query ... ok
test tests::test::test_casting ... ok
test tests::test::test_closures_and_pipelines ... ok
test semantic::resolver::test::test_frames_and_names ... ok
test tests::test::test_custom_transforms ... ok
test tests::test::test_dates ... ok
test tests::test::test_array ... ok
test tests::test::test_datetime ... ok
test tests::test::test_datetime_parsing ... ok
test tests::test::test_datetime_sqlite ... ok
test tests::test::test_error_code ... ok
test semantic::transforms::tests::test_aggregate_positional_arg ... ok
test tests::test::test_excess_columns ... ok
test tests::test::test_direct_table_references ... ok
test tests::test::test_case ... ok
test tests::test::test_distinct_on ... ok
test tests::test::test_filter_and_select_unchanged_alias ... ok
test tests::test::test_double_aggregate ... ok
test tests::test::test_double_stars ... ok
test sql::srq::test::test_ctes_of_pipeline ... ok
test tests::test::test_append ... ok
test tests::test::test_f_string ... ok
test tests::test::test_header ... ok
test tests::test::test_filter_and_select_changed_alias ... ok
test tests::test::test_inline_tables ... ok
test tests::test::test_bare_s_string ... ok
test tests::test::test_group_all ... ok
test tests::test::test_filter ... ok
test tests::test::test_intervals ... ok
test tests::test::test_from_json ... ok
test tests::test::test_ident_escaping ... ok
test tests::test::test_into ... ok
test tests::test::test_from_text ... ok
test tests::test::test_interval ... ok
test tests::test::test_literal ... ok
test tests::test::test_loop ... ok
test tests::test::test_loop_2 ... ok
test tests::test::test_lower ... ok
test tests::test::test_join ... ok
test tests::test::test_header_target_error ... ok
test tests::test::test_name_resolving ... ok
test tests::test::test_lineage ... ok
test tests::test::test_nonatomic_table ... ok
test tests::test::test_numbers ... ok
test tests::test::test_output_column_deduplication ... ok
test tests::test::test_params ... ok
test tests::test::test_name_shadowing ... ok
test tests::test::test_prql_to_sql_table ... ok
test tests::test::test_prql_to_sql_2 ... ok
test tests::test::test_ranges ... ok
test tests::test::test_read_parquet_duckdb ... ok
test tests::test::test_regex_search ... ok
test tests::test::test_nonatomic ... ok
test tests::test::test_name_inference ... ok
test tests::test::test_prql_to_sql_1 ... ok
test tests::test::test_rn_ids_are_unique ... ok
test tests::test::test_sql_of_ast_2 ... ok
test tests::test::test_same_column_names ... ok
test tests::test::test_sql_of_ast_1 ... ok
test tests::test::test_exclude_columns ... ok
test tests::test::test_static_analysis ... ok
test tests::test::test_strings ... ok
test tests::test::test_nulls ... ok
test tests::test::test_sorts ... ok
test tests::test::test_sql_options ... ok
test tests::test::test_intersect ... ok
test tests::test::test_table_definition_with_expr_call ... ok
test tests::test::test_distinct ... ok
test tests::test::test_target_clickhouse ... ok
test tests::test::test_stdlib ... ok
test tests::test::test_toposort ... ok
test tests::test::test_quoting ... ok
test tests::test::test_unused_alias ... ok
test tests::test::test_type_as_column_name ... ok
test tests::test::test_table_alias ... ok
test tests::test::test_upper ... ok
test tests::test::test_window_functions_00 ... ok
test tests::test::test_table_names_between_splits ... ok
test tests::test::test_window_functions_03 ... ok
test tests::test::test_window_functions_02 ... ok
test tests::test::test_window_functions_04 ... ok
test tests::test::test_window_functions_05 ... ok
test tests::test::test_window_functions_07 ... ok
test tests::test::test_window_functions_09 ... ok
test tests::test::test_window_functions_06 ... ok
test tests::test::test_window_functions_08 ... ok
test tests::test_bad_error_messages::array_instead_of_tuple ... ok
test tests_lib::test_target_from_str ... ok
test utils::toposort::tests::dag_with_cycle ... ok
test utils::toposort::tests::normal_sort ... ok
test utils::toposort::tests::normal_sort_2 ... ok
test utils::toposort::tests::parallel_when_ambiguous ... ok
test tests_lib::test_target_names ... ok
test utils::toposort::tests::with_root ... ok
test utils::test_write_ident_part ... ok
test tests::test::test_window_functions_10 ... ok
test tests::test::test_targets ... ok
test tests::test_error_messages::test_bad_function_type ... ok
test tests::test_error_messages::test_basic_type_checking ... ok
test tests::test_error_messages::test_hint_missing_args ... ok
test tests::test_error_messages::test_regex_dialect ... ok
test tests::test_error_messages::test_union_all_sqlite ... ok
test tests::test::test_precedence ... ok
test tests::test::test_remove ... ok
test tests::test_bad_error_messages::test_bad_error_messages ... ok
test tests::test::test_table_s_string ... ok
test tests::test_error_messages::test_errors ... ok
test tests::test::test_take ... ok

test result: ok. 188 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.80s

     Running tests\integration\main.rs (target\debug\deps\integration-639e5134837e2197.exe)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests prql-compiler

running 5 tests
test src\lib.rs - (line 53) ... ignored
test src\sql\srq\ast.rs - sql::srq::ast::SqlTransform::Super (line 73) ... ignored
test src\lib.rs - compile (line 111) ... ok
test src\lib.rs - (line 39) ... ok
test src\lib.rs - ReadmeDoctests (line 272) ... ok

test result: ok. 3 passed; 0 failed; 2 ignored; 0 measured; 0 filtered out; finished in 3.00s

info: no snapshots to review
```

...And prqlc was failed.

```sh
❯ cargo run -p prqlc -- compile -
   Compiling winapi v0.3.9
   Compiling serde v1.0.163
   Compiling strsim v0.10.0
   Compiling tracing-core v0.1.31
   Compiling backtrace v0.3.67
   Compiling log v0.4.17
   Compiling sharded-slab v0.1.4
   Compiling syn v2.0.17
   Compiling thread_local v1.1.7
   Compiling terminal_size v0.2.6
   Compiling pin-project-lite v0.2.9
   Compiling crossbeam-utils v0.8.15
   Compiling windows-sys v0.45.0
   Compiling eyre v0.6.8
   Compiling fastrand v1.9.0
   Compiling owo-colors v3.5.0
   Compiling clap_builder v4.3.0
   Compiling indenter v0.3.3
   Compiling filetime v0.2.21
   Compiling windows-sys v0.42.0
   Compiling tracing v0.1.37
   Compiling humantime v2.1.0
   Compiling anyhow v1.0.71
   Compiling crossbeam-channel v0.5.8
   Compiling tracing-subscriber v0.3.17
   Compiling tempfile v3.5.0
   Compiling tracing-error v0.2.0
   Compiling color-spantrace v0.2.0
   Compiling color-eyre v0.6.2
   Compiling winapi-util v0.1.5
   Compiling stacker v0.1.15
   Compiling atty v0.2.14
   Compiling chumsky v0.9.2
   Compiling same-file v1.0.6
   Compiling termcolor v1.2.0
   Compiling walkdir v2.3.3
   Compiling notify v6.0.0
   Compiling env_logger v0.10.0
   Compiling serde_derive v1.0.163
   Compiling clap_derive v4.3.0
   Compiling strum_macros v0.25.0
   Compiling enum-as-inner v0.6.0
   Compiling strum v0.25.0
   Compiling clap v4.3.0
   Compiling clap_complete v4.3.0
   Compiling clio v0.3.1
   Compiling colorchoice-clap v1.0.0
   Compiling clap_complete_fig v4.3.0
   Compiling clap_complete_nushell v0.1.11
   Compiling clap_complete_command v0.5.1
   Compiling sqlparser v0.34.0
   Compiling serde_json v1.0.96
   Compiling serde_yaml v0.9.21
   Compiling semver v1.0.17
   Compiling csv v1.2.1
   Compiling minijinja v0.31.0
   Compiling prql-compiler v0.8.1 (C:\Users\foo\Downloads\prql-main\prql-compiler)
   Compiling prqlc v0.8.1 (C:\Users\foo\Downloads\prql-main\prql-compiler\prqlc)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 22s
     Running `target\debug\prqlc.exe compile -`
Enter PRQL, then press ctrl-z to compile:

from employees
filter gross_cost > 0
group {title} (
  aggregate {
    ct = count s"*",
  }
)
sort ct
filter ct > 200
take 20
sort ct
filter ct > 200
take 20
sort ct
filter ct > 200
take 20
sort ct
filter ct > 200
take 20

thread 'main' has overflowed its stack
error: process didn't exit successfully: `target\debug\prqlc.exe compile -` (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)
```

> Edit: I guess you've been using the dev container!

Yeah, I don't even have Git installed on Windows because I do all my programming work on WSL2.

> I hadn't known it was difficult to build on Windows

In my opinion this is difficult even on Linux. This means that an additional installation of cmake is needed just for libduckdb-sys, and it takes a very long time to compile libduckdb-sys.......

**Comment by max-sixty** [comment]
I added https://github.com/PRQL/prql/pull/2901 to see if that got us closer.

I had thought it was doing exactly the same thing. But actually `prqlc` is doing a bit more because it's handling multiple sources:
- https://github.com/prql/prql/blob/a74d150ff5037e21f9903c230ecd3a64694c3fcf/prql-compiler/prqlc/src/cli.rs#L349
- https://github.com/prql/prql/blob/8d2a55d23a81e17c8fd9a632a267ae95f21083a3/prql-compiler/src/lib.rs#L131

So maybe that's the distinction...

---

> In my opinion this is difficult even on Linux. This means that an additional installation of cmake is needed just for libduckdb-sys, and it takes a very long time to compile libduckdb-sys.......

I disabled the test by default at https://github.com/PRQL/prql/pull/2899 and updated the docs.

I agree `duckdb` is very expensive to build. I liked the idea of being able to run everything with `cargo test`, rather than having lots of modes, but yes, in retrospect, it probably was too heavy to include by default.

**Pull request merged**
