### PR TITLE
devops(devcontainer): add sqlite3 and duckdb cli

### PR DESCRIPTION
**Pull request by eitsupi**
It is useful to have these installed when checking prqlc behavior.

### CODE REVIEW

**Comment by eitsupi** [comment]
(I originally wanted to install usql, but unfortunately there was no binary release for arm64 Linux)

**Comment by max-sixty** [comment]
Does DuckDB take ages to compile & install? Or it copies a binary? 

Guessing the latter given your comment re `usql`. Otherwise we could add to the base image...

**Comment by eitsupi** [comment]
Yes, simply download the latest version of the single binary from the GitHub release page. It should take less than a few seconds.

**Comment by max-sixty** [comment]
Great!

**Review by max-sixty — APPROVED** [review]

**Pull request merged**
