### PR TITLE
devops: rustfmt only runs on staged files

### PR DESCRIPTION
**Pull request by m-span**
files were starting to deviate from rustfmt, making diffs of other branches more complex

fmt stage is now written within yaml file, so no more network issues

by using `rustfmt` instead of `cargo fmt`, the pre-commit fmt only runs on staged files

all files have also been run against `rustfmt`

### CODE REVIEW

**Comment by max-sixty** [comment]
What's the advantage of running `rustfmt` over `cargo fmt`? I haven't seen projects do the former...

Why would they give different outputs?

**Comment by max-sixty** [comment]
@m-span is there any chance you might have local configs which cause different outputs? If I pull this branch and then run `pre-commit run -a`, the rust code all resets back to that of `main`

**Comment by m-span** [comment]
`cargo fmt` always formats all rust files in the full project. `rustfmt` can be fed a list of files (from pre-commit) so that it only formats the files that have changed. This is a known issue/difference for pre-commit.

What is the intended developer experience? Every PR must have all rust files formatted, or each PR only expects changed files to be formatted?

**Comment by m-span** [comment]
I ask because in order for other branches to 'pass', they have to cargo fmt files that weren't even affected? If this is a hard requirement, how did it get desynced?

**Comment by max-sixty** [comment]
> I ask because in order for other branches to 'pass', they have to cargo fmt files that weren't even affected? If this is a hard requirement, how did it get desynced?

I don't think it is desynced! 

Expressed as humbly as possible — yours is the first system to have these formatting issues — are you sure it's not something up with your end?

From above:

> @m-span is there any chance you might have local configs which cause different outputs? If I pull this branch and then run `pre-commit run -a`, the rust code all resets back to that of `main`

For a hard test — CI checks `cargo fmt` passes in CI on `main`...

**Comment by max-sixty** [comment]
Is there possibly a config file in one of these locations:

> If none of these directories contain such a file, both your home directory and a directory called rustfmt in your global config directory (e.g. .config/rustfmt/) are checked as well.

From https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=

**Comment by m-span** [comment]
problem was with my environment

**Pull request closed without merging**
