### PR TITLE
fix: Detect tty for prqlc prompt

### LINKED ISSUE #3228: Can the `prqlc` prompt only show when waiting?
### What's up?

We have a prompt which shows when running `prqlc compile`, to avoid appearing to hang while waiting for an input — "Enter PRQL, then press ctrl-d to compile:`" 

I think that's great, I quite dislike the confusion in CLIs where it's unclear if they're thinking or waiting. IIRC, doing this is in a bunch of "CLI best practices" guides

But it also shows `Enter PRQL, then press ctrl-d to compile:` when something is piped in:

```sh
$ echo "from artists" | prqlc compile -
Enter PRQL, then press ctrl-d to compile:

SELECT
  *
FROM
  artists

-- Generated by PRQL compiler version:0.9.2 (https://prql-lang.org)
```

Weirdly I can't remember that happening previously; do others?

Is there some way we can only show when it's waiting, and not when piping text in?

### PR DESCRIPTION
**Pull request by max-sixty**
Closes https://github.com/PRQL/prql/issues/3228

### CODE REVIEW

**Comment by max-sixty** [comment]
FYI @aj-bagwell — not sure if this is a helpful @ or not — feel free to ignore if not. 

The approach in https://github.com/PRQL/prql/pull/2885/files#diff-5042ecb23fbc2e8750e6452e008e9e96007bc06be4dff012653aedeaede02865R410 didn't seem to detect a `tty` correctly (or at least how I'm thinking about a TTY, where someone is typing into stdin, rather than piping text in). 

More details in #3228. I spent 20 minutes looking through dependencies — it seems like `clio` is calling the same code, though the code changes slightly by versions, so I'm likely missing something.

We're v happy to stick with this for a bit while upgrades percolate through the ecosystem.

**Review by eitsupi — COMMENTED** [review]
Thanks for working on this!
Could we add a test for this?

**Comment by max-sixty** [comment]
> Thanks for working on this! Could we add a test for this?

For sure we should have one — but it should be in our tests already! e.g. https://github.com/PRQL/prql/blob/9743446298ce4e72424239c234288a6c54173d74/crates/prqlc/tests/test.rs#L65

I think possibly it isn't picking it up because it's not a terminal, whereas the error was happening while we were in a terminal but not a tty? (I'm not tight on these concepts...)

**Comment by eitsupi** [comment]
Thank you for pointing that out. It seems difficult to test this....

**Pull request merged**
