### PR TITLE
build: tweak megalinter config for sql

### PR DESCRIPTION
**Pull request by eitsupi**
Part of #1994

- In this project `tsql` is not used, so `tsqllint` should be disabled.
- Add `.sqlfluff` to enable `sqlfluff`, and formatting the SQL file to pass `sqlfluff`'s check.

### CODE REVIEW

**Comment by eitsupi** [comment]
MegaLinter also includes `sqllfluff`, but it is not currently enabled.
I am wondering if this is worth enabling.

Current errors from `sqlfluff`:

```sh
$ sqlfluff lint --dialect ansi  prql-compiler/tests/integration/data/chinook/schema.sql

== [prql-compiler/tests/integration/data/chinook/schema.sql] FAIL                                                       
L:   1 | P:   1 | LT05 | Line is too long (225 > 80).
                       | [layout.long_lines]
L:   1 | P:  22 | LT01 | Expected single whitespace between naked identifier and
                       | start bracket '('. [layout.spacing]
L:   2 | P:   1 | LT05 | Line is too long (251 > 80).
                       | [layout.long_lines]
L:   2 | P:  23 | LT01 | Expected single whitespace between naked identifier and
                       | start bracket '('. [layout.spacing]
L:   2 | P: 132 | RF04 | Keywords should not be used as identifiers.
                       | [references.keywords]
L:   3 | P:   1 | LT05 | Line is too long (288 > 80).
                       | [layout.long_lines]
L:   3 | P:  23 | LT01 | Expected single whitespace between naked identifier and
                       | start bracket '('. [layout.spacing]
L:   3 | P: 193 | RF04 | Keywords should not be used as identifiers.
                       | [references.keywords]
L:   4 | P:   1 | LT05 | Line is too long (189 > 80).
                       | [layout.long_lines]
L:   4 | P:  20 | LT01 | Expected single whitespace between naked identifier and
                       | start bracket '('. [layout.spacing]
L:   4 | P:  39 | RF06 | Unnecessary quoted identifier "name".
                       | [references.quoting]
L:   4 | P: 132 | RF06 | Unnecessary quoted identifier "milliseconds".
                       | [references.quoting]
L:   5 | P:  20 | LT01 | Expected single whitespace between naked identifier and
                       | start bracket '('. [layout.spacing]
L:   6 | P:  20 | LT01 | Expected single whitespace between naked identifier and
                       | start bracket '('. [layout.spacing]
L:   6 | P:  39 | RF06 | Unnecessary quoted identifier "name".
                       | [references.quoting]
L:   7 | P:  28 | LT01 | Expected single whitespace between naked identifier and
                       | start bracket '('. [layout.spacing]
L:   8 | P:  23 | LT01 | Expected single whitespace between naked identifier and
                       | start bracket '('. [layout.spacing]
L:   8 | P:  45 | RF06 | Unnecessary quoted identifier "name".
                       | [references.quoting]
L:   9 | P:  25 | LT01 | Expected single whitespace between naked identifier and
                       | start bracket '('. [layout.spacing]
L:   9 | P:  49 | RF06 | Unnecessary quoted identifier "name".
                       | [references.quoting]
L:  10 | P:  21 | LT01 | Expected single whitespace between naked identifier and
                       | start bracket '('. [layout.spacing]
L:  10 | P:  41 | RF06 | Unnecessary quoted identifier "name".
                       | [references.quoting]
L:  11 | P:   1 | LT05 | Line is too long (127 > 80).
                       | [layout.long_lines]
L:  11 | P:  27 | LT01 | Expected single whitespace between naked identifier and
                       | start bracket '('. [layout.spacing]
```

**Comment by max-sixty** [comment]
Given that most of our SQL is output from the PRQL compiler, I don't know how we'd manage that. (Except for outputting better SQL!)

**Comment by eitsupi** [comment]
> Given that most of our SQL is output from the PRQL compiler, I don't know how we'd manage that. (Except for outputting better SQL!)

For now, the only target is https://github.com/PRQL/prql/blob/76bd7a43298330a45c05e5fa900d554d3a6d0eb4/prql-compiler/tests/integration/data/chinook/schema.sql.

**Comment by max-sixty** [comment]
> For now, the only target is https://github.com/PRQL/prql/blob/76bd7a43298330a45c05e5fa900d554d3a6d0eb4/prql-compiler/tests/integration/data/chinook/schema.sql.

Ah OK, we could enable it, then. I guess it's not looking at our snapshots since they don't have a `.sql` extension

**Comment by eitsupi** [comment]
`sqlfluff` is now enabled and has passed linting.
If it looks good, it can be merged.

**Comment by max-sixty** [comment]
Great! I'll hit the button

**Pull request merged**
