### PR TITLE
ci: push devcontainer base docker image when releasing

### PR DESCRIPTION
**Pull request by eitsupi**
https://github.com/PRQL/prql/pull/1893#discussion_r1128934864

### CODE REVIEW

**Comment by eitsupi** [comment]
As noted on MegaLinter, are there problems with the release workflow? (Also noted on actionlint playground below)
https://rhysd.github.io/actionlint/

```log
✅ Linted [ACTION] files with [actionlint]: Found 3 non blocking error(s) - (0.11s) (expand for details)
  - Using [actionlint v1.6.23] https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/action_actionlint
  - MegaLinter key: [ACTION_ACTIONLINT]
  - Rules config: identified by [actionlint]
  - Number of files analyzed: [2]
  --Error detail:
  .github/workflows/release.yaml:47:52: property "refname" is not defined in object type {action: string; action_path: string; action_ref: string; action_repository: string; action_status: string; actor: string; actor_id: string; api_url: string; base_ref: string; env: string; event: object; event_name: string; event_path: string; graphql_url: string; head_ref: string; job: string; job_workflow_sha: string; path: string; ref: string; ref_name: string; ref_protected: string; ref_type: string; repository: string; repository_id: string; repository_owner: string; repository_owner_id: string; repositoryurl: string; retention_days: number; run_attempt: string; run_id: string; run_number: string; server_url: string; sha: string; token: string; triggering_actor: string; workflow: string; workflow_ref: string; workflow_sha: string; workspace: string} [expression]
     |
  47 |           version: ${{ github.ref_type == 'tag' && github.refname || 0 }}
     |                                                    ^~~~~~~~~~~~~~
  .github/workflows/release.yaml:76:52: property "refname" is not defined in object type {action: string; action_path: string; action_ref: string; action_repository: string; action_status: string; actor: string; actor_id: string; api_url: string; base_ref: string; env: string; event: object; event_name: string; event_path: string; graphql_url: string; head_ref: string; job: string; job_workflow_sha: string; path: string; ref: string; ref_name: string; ref_protected: string; ref_type: string; repository: string; repository_id: string; repository_owner: string; repository_owner_id: string; repositoryurl: string; retention_days: number; run_attempt: string; run_id: string; run_number: string; server_url: string; sha: string; token: string; triggering_actor: string; workflow: string; workflow_ref: string; workflow_sha: string; workspace: string} [expression]
     |
  76 |           version: ${{ github.ref_type == 'tag' && github.refname || 0 }}
     |                                                    ^~~~~~~~~~~~~~
  .github/workflows/release.yaml:104:21: property "build" is not defined in object type {} [expression]
      |
  104 |           snap: ${{ steps.build.outputs.snap }}
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~
```

Might need to fix this in another PR.

**Review by max-sixty — APPROVED** [review]
Thank you!

**Comment by max-sixty** [comment]
Great spot from `actionlint`!

~That looks like a good one. Given how much I'm editing that, I might add that to `.pre-commit` too, so I can have it locally, if that's OK...~ Actually this is where MegaLinter comes in handy — it's actually not a self-install in pre-commit; instead it relies on an external binary — which is not friendly for other contributors. So let's rely on MegaLinter only. Should we turn on errors for that?

**Comment by eitsupi** [comment]
> Actually this is where MegaLinter comes in handy — it's actually not a self-install in pre-commit; instead it relies on an external binary — which is not friendly for other contributors. So let's rely on MegaLinter only. Should we turn on errors for that?

Yeah, the actionlint warnings seem to be mostly gone in main branch, so I'll work on getting its error enabled after this.
actionlint really helps, as debugging GitHub Actions is sometimes tough.

**Pull request merged**
