### PR TITLE
docs: website theme

### PR DESCRIPTION
**Pull request by aljazerzen**
My wife said that the website looks like the barber shop thing and suggested this instead:

image

I quite like it, but I may be a bit biased :D

### CODE REVIEW

**Comment by snth** [comment]
You mean like this?
image

I mean I kinda see where she's coming from but I don't see it as a big issue.

Your theme is too dark for my liking. I'd happily defer to a designer on this though.

**Comment by richb-hanover** [comment]
I like the barber pole design. It's distinctive and looks "bright". It's easy to read the text. I think @aljazerzen's proposal is too dark (as is the pane at the bottom of the home page - I noticed that it didn't seem to belong.)

Do we have a designer in mind? I also would defer to them.

**Comment by max-sixty** [comment]
I trust @aljazerzen 's wife more than me! FWIW I rather like the barbershop background. "Cutting SQL into shape"...

That said, if someone who has contributed to the website (or their partner...) has a designer in mind and would like to manage a refresh of the page, let me know, and I can sort out the funding.

**Comment by aljazerzen** [comment]
It seems that current design is good enough, we can link back to this PR when needed.

**Pull request closed without merging**
