### PR TITLE
docs: Factor "syntax.md" into /syntax folder

### PR DESCRIPTION
**Pull request by richb-hanover**
This PR factors the single top-level _syntax.md_ into its own `/syntax` folder, with each of the components described in its own file. 

Extremely small editorial changes to the component files in the `/syntax` folder so the only diff compare is to ensure that I got all the links right.

This PR does _not_ address the Precedence/Parentheses question; that's next, but it's easier to see now that the files are more focused

### CODE REVIEW

**Comment by eitsupi** [comment]
This is great because every time I opened the book I was lost as to where the operators were listed!

**Review by aljazerzen — APPROVED** [review]
This bothered me too, thanks for factoring

**Comment by richb-hanover** [comment]
@aljazerzen @eitsupi Can either of you see why the test is failing?  Thanks.

**Comment by eitsupi** [comment]
Perhaps the snapshots of the snapshot tests needs to be updated?

**Comment by max-sixty** [comment]
Could we run `task test-rust`?

**Comment by max-sixty** [comment]
This ranks as the most universally appreciated PR @richb-hanover !

**Comment by aljazerzen** [comment]
With many things that were added to the book, we should think about reorganizing it so it reads more like a book and not like a reference manual.

**Comment by max-sixty** [comment]
> With many things that were added to the book, we should think about reorganizing it so it reads more like a book and not like a reference manual.

Yes interesting point.

WDYT the best way of doing that is?

I could imagine being more focused on some canonical examples?

(maybe we open a new issue if necessary)

**Comment by richb-hanover** [comment]
@max-sixty Thanks for merging. You probably saw that the backport failed

**Pull request merged**
