### PR TITLE
docs: Link Prefect and DuckDB

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Comment by eitsupi** [comment]
I am reminded of an outdated statement in this document.
Could you make the following update? (`pyprql.to_sql` -> `prql_python.compile`)

https://github.com/PRQL/prql/blob/7a33ebe3e5c03514e8ac0960cecc73f2a8264053/web/book/src/integrations/prefect.md?plain=1#L13-L15

**Comment by vanillajonathan** [comment]
@eitsupi Done!

**Comment by eitsupi** [comment]
Thanks!

**Comment by max-sixty** [comment]
Thanks a lot @vanillajonathan !

**Pull request merged**
