### PR TITLE
refactor: FormattedError

### PR DESCRIPTION
**Pull request by max-sixty**
Not the most essential code change — and open to feedback on whether it's useful on net! — but trying to make the interface simpler as I was adding a test for errors:
- Moved related functions into a Trait
- Renamed the Trait containing the error message from `FormattedError` to `ErrorMessage`, since it's not an `Error` type (maybe there are better alternatives though?)

Still not confident about the overall interface. Should `compile` return a `Result` whose `Error` type has the full message on? At that point we have `source`, albeit not the `source_id`. Or should we have one `Error` type and one "Error Output" (i.e. `FormattedError` / `ErrorMessage`)

### CODE REVIEW

**Comment by max-sixty** [comment]
(this builds on https://github.com/prql/prql/pull/1181)

**Comment by aljazerzen** [comment]
I like this trait approach. Renaming is also better now.

Looking at this I'd say that compile could format the error by default. It's a convenience wrapper function anyway -- if you don't want to run formatting you can still call underlying processing functions.

Related to #1167

**Comment by max-sixty** [comment]
OK great. 

- If `compile` returns `Result<String, ErrorMessage>`, should `ErrorMessage` (nee `FormattedError`) implement the `StdError` trait? Currently it doesn't, it's just a normal Struct.
- The alternative would be a single `Error` type which has a `source` & `source_id` of `Optional`, and can produce an  error message where those are `Some`.
  - We may need to implement this on `anyhow::Error`, given we return that from almost all functions (and it sometimes contains our own `Error`, not always though)
- If this is a lot of decisions, happy to merge this and then decide more as we gain more experience — not the most critical part of our code

**Comment by aljazerzen** [comment]
I don't any reasons to change current setup:
- std::error::Error trait is meant for errors in sense of exceptions that will provide info like causes and descriptions and backtrace to developers. We don't need that - we need structured data that is passed to the frontend (or the CLI)
- having source in the Error may be too costly memory-wise. It could be a reference, borrowing the input, but I don't want to deal with that.

Current setup allows you to call any amount of functions and at the end, optionally format the error. This is modular and has ability not to format errors in if you want for example check validity of the source at every keystroke.

**Comment by max-sixty** [comment]
OK cool @aljazerzen , that sounds v reasonable, I'll finish this off at the weekend

**Comment by max-sixty** [comment]
> Looking at this I'd say that compile could format the error by default. It's a convenience wrapper function anyway -- if you don't want to run formatting you can still call underlying processing functions.

I'm actually not sure this quite works — then it's not possible to call `.compile(...)?`, because the `?` requires `ErrorMessage` to implement `StdError`.

If you agree, I'll do the "close" thing now, and then we can iterate on it later?

**Pull request merged**
