### PR TITLE
tweak(docs): Align `operators` vs `operations` in docs

### PR DESCRIPTION
**Pull request by max-sixty**

### CODE REVIEW

**Comment by max-sixty** [comment]
@aljazerzen the tiniest change but wanted you to check it wasn't me undoing something you did intentionally

**Review by aljazerzen — APPROVED** [review]
Yea, ok.

Rename the file too?

**Comment by max-sixty** [comment]
> Rename the file too?

Isn't `operators` the correct name for the file?

**Comment by aljazerzen** [comment]
Oh yes it is, I misunderstood what you changed.

**Pull request merged**
