### PR TITLE
docs: Tweak "select" wording

### PR DESCRIPTION
**Pull request by richb-hanover**
This tracks the conversation in https://github.com/prql/prql/pull/1290 to update the language re: `select` and loss of the table/namespace alias

### CODE REVIEW

**Comment by richb-hanover** [comment]
NB: I prefer the description in the tweak-select-wording branch... Thanks!

**Comment by max-sixty** [comment]
We need to merge main into this and resolve the conflicts :)

That can be done locally or on GH: 
image

**Comment by richb-hanover** [comment]
@max-sixty I still need help here... The `test-rust` test is failing, and it looks as if it's related to the new example code I created. But I don't understand what needs to change... Thanks!

**Comment by max-sixty** [comment]
> @max-sixty I still need help here... The `test-rust` test is failing, and it looks as if it's related to the new example code I created. But I don't understand what needs to change... Thanks!

Does running `task test-rust` locally solve the issue?

**Comment by max-sixty** [comment]
Changes look good! The rust tests are failing because we snapshot and test the code snippets in the book, and this changes those. `task test-rust` will run and accept those changes, so we can see the diff in the PR

**Review by max-sixty — APPROVED** [review]

**Comment by richb-hanover** [comment]
Yes, running `task test-rust` locally, then re-pushing the (small number of) modified `.snap` files made the magic work...

**Comment by max-sixty** [comment]
Thanks a lot @richb-hanover !

**Comment by richb-hanover** [comment]
@max-sixty I see that the new text has been merged into `main`. But the [Book still shows the old wording.](https://prql-lang.org/book/transforms/select.html) Am I missing something? Thanks.

**Comment by max-sixty** [comment]
Great spot. Something did seem to go wrong with the github pages deployment: https://github.com/prql/prql/actions/runs/3744549189/jobs/6358051621, the "Deploy to GitHub Pages" didn't run.

I just kicked it off again, let's see if that works, otherwise I'll debug

**Pull request merged**
