### PR TITLE
refactor: ast rename

### PR DESCRIPTION
**Pull request by m-span**
more cleanups, rename srq to pq, replace ast import references, update markdown

### CODE REVIEW

**Review by max-sixty — APPROVED** [review]
Super, thanks!

**Review by aljazerzen — APPROVED** [review]
Thanks, looks great, by which I mean minimal. This probably has decent chances to merge into `feat-types` without major problems.

**Comment by max-sixty** [comment]
Bleh, we got merge conflicts. Probably my fault for not merging the `pow` PR sooner. @m-span if you don't get to it in the next day or so I'll fix them up.

**Comment by aljazerzen** [comment]
I'm resolving these, it'll be less pain merging other PRs I have lined up this way.

**Comment by m-span** [comment]
Thanks for the merge conflict help. 
I was trying to keep this as small as possible, and it should make things cleaner for object referencing moving forward.

**Comment by max-sixty** [comment]
~Cool! Shall we hit the button?~

I'll hit the button :)

**Pull request merged**
