### PR TITLE
refactor: cleanup literal Display trait

### PR DESCRIPTION
**Pull request by aljazerzen**
Moves display of literal to prql_ast crate.
This code is quite inherent to Literal, so it can reside in prql_ast.
Especially because it simplifies other parts of the codebase.

### CODE REVIEW

**Comment by not-my-profile** [comment]
I think it makes more sense to have that logic be part of the PRQL codegen/formatter.

**Comment by max-sixty** [comment]
> I think it makes more sense to have that logic be part of the PRQL codegen/formatter.

Are the orphaning rules an issue here? i.e. that we can't implement `Display` on structs from another crate?

**Comment by not-my-profile** [comment]
Yes of course they are but that can be solved via a newtype, as I did in 2017621e8dea0ed662ec0a88a760293de9181086, which this PR essentially seeks to revert.

To clarify what I had in mind: I think we should get rid of this Display impl entirely and rather implement it via the codegen trait ... (which should also be adjusted since it currently requires needless string allocations rather than operating on e.g. `std::fmt::Write`).

**Comment by max-sixty** [comment]
> Yes of course they are but that can be solved via a newtype, as I did in [2017621](https://github.com/PRQL/prql/commit/2017621e8dea0ed662ec0a88a760293de9181086), which this PR essentially seeks to revert.

Yes, I guess this is a case of the tradeoff in https://github.com/PRQL/prql/issues/3108#issuecomment-1652202443

---

BTW @not-my-profile — just to emphasize — I think we're all v happy you're here and have already made such an impact. 

It's possible that we don't immediately end up exactly where you want, as we compromise on some of these tradeoffs. I hope you're OK with that. Nothing is fixed, and we can revisit in the future.

**Comment by not-my-profile** [comment]
I personally think that keeping the codegen together and out of prql_ast is much more preferable than slightly simplifying the code by getting rid of a newtype ... especially when the newtype can be gotten rid of by just properly implementing (a better) codegen trait for it. You're welcome to any tradeoffs you deem reasonable ... I just disagree with this one.

**Comment by aljazerzen** [comment]
Motivation here is that `prql_parser::lexer::Token` needs a display, so it can produce hints and error messages as "expected let, but found an identifier". The problem is that is contains `prql_ast::Expr::Literal`. Because `Token` is in parser and `Literal` is in ast, they cannot depend on codegen, which is in the main crate.

So this PR essentially says "tokens and literals are so simple constructs that they can be converted to strings on-the-fly. They don't require the whole codegen machinery, which deals with precedence and indentation".

**Comment by not-my-profile** [comment]
I think that dependency problem can very simply be resolved with just a3d61a8737424cfe76a5f8853d097be24bbc88a3 (the first commit from #3141). We already have the spans, so I don't think repeating the literal in the error message really adds anything.

**Comment by aljazerzen** [comment]
We can do without this refactor and avoid merge conflicts.

**Pull request closed without merging**
