### PR TITLE
refactor: rename `types::TupleField` to `types::TyTupleField`

### PR DESCRIPTION
**Pull request by aljazerzen**
This PR is the first commit in series of trying to formalize what expression aliases are (i.e. `x` in `select x = my_col`).

The idea was that these are all just tuple field names, but it turns out this is not the case, so I'm abandoning that idea.

This PR is just a refactor that makes sense on its own, remaining commits are on branch `feat-tuple-field`.

### CODE REVIEW

**Comment by vanillajonathan** [comment]
What does "Ty" mean?

**Comment by aljazerzen** [comment]
type

We have a bunch of other things named this way.

**Comment by vanillajonathan** [comment]
It is far from obvious that "Ty" means "Type". It's an abbreviation I've never heard of. Seems not so helpful to short down a four-letter word to a two-letter abbreviation. Rust has a convention of appending "Kind" as a suffix on enums so maybe this would be better named `TupleFieldKind`.

**Comment by aljazerzen** [comment]
Well, it is a compiler abbreviation, I guess. Here I wanted to distinguish between the "TupleField expression" and "TupleField type"

Rust's ast does use it:

https://doc.rust-lang.org/beta/nightly-rustc/rustc_ast/ast/struct.Ty.html

We use it:

https://github.com/PRQL/prql/blob/main/prqlc/prqlc-ast/src/types.rs#L10

https://github.com/PRQL/prql/blob/main/prqlc/prqlc-ast/src/types.rs#L86

**Pull request merged**
