### PR TITLE
build: cleanup nix flake

### PR DESCRIPTION
**Pull request by aljazerzen**

### CODE REVIEW

**Comment by max-sixty** [comment]
FYI responded on Discord: https://discord.com/channels/936728116712316989/1207023570560090133/1207779360145408060

**Comment by max-sixty** [comment]
(Back from discord)

Still same issue:

```

   Compiling connector_arrow v0.3.0
error: linking with `cc` failed: exit status: 1
  |
  = note: env -u IPHONEOS_DEPLOYMENT_TARGET -u TVOS_DEPLOYMENT_TARGET LC_ALL="C" PATH="/nix/store/idppma96mlgcsfkdka14ln7kanr805dq-clippy-stable-with-std-2024-02-08/lib/rustlib/a
arch64-apple-darwin/bin:/nix/store/y432q34aj5h9qn5qzm4w066j5l5dhmd2-clang-wrapper-11.1.0/bin:/nix/store/gcbmg7a0fhdcda42g7qp7ngqcix7bax5-clang-11.1.0/bin:/nix/store/xyagncilqx57c
ljac32w9ld3kkn276d3-coreutils-9.3/bin:/nix/store/qridnykybxbk74v5akvbpmyz66rhkxzk-cctools-binutils-darwin-wrapper-11.1.0-973.0.1/bin:/nix/store/0i2sn40fp7mncwzah2mryjkdy3wx4z8r-c
ctools-binutils-darwin-11.1.0-973.0.1/bin:/nix/store/4734r30asd6g6f8dglq3bc6c09xs5nmk-cargo-stable-2024-02-08/bin:/nix/store/idppma96mlgcsfkdka14ln7kanr805dq-clippy-stable-with-s
td-2024-02-08/bin:/nix/store/zpfkj02xskvxh2814z0ikd8jnjqsq54v-rust-stable-with-std-2024-02-08/bin:/nix/store/kish8q613m4fn9h1l4qz7x5b7ib7ilkh-rustfmt-preview-stable-2024-02-08/bi
n:/nix/store/ivn46k26z1hhf990njn7z34v2jwkw39p-rust-analyzer-p

...

lib/aarch64-apple-darwin/lib/libcfg_if-9f474e4309122405.rlib" "/nix/store/mjgy0lbj4gym3w40g28ijkgsfa5l7wiv-rust-std-stable-2024-02-08/lib/rustlib/aarch64-apple-darwin/lib/liblibc-0bfd536a501ea558.rlib" "/nix/store/mjgy0lbj4gym3w40g28ijkgsfa5l7wiv-rust-std-stable-2024-02-08/lib/rustlib/aarch64-apple-darwin/lib/liballoc-d56621fef414e9f8.rlib" "/nix/store/mjgy0lbj4gym3w40g28ijkgsfa5l7wiv-rust-std-stable-2024-02-08/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_core-60d6843fd08e9533.rlib" "/nix/store/mjgy0lbj4gym3w40g28ijkgsfa5l7wiv-rust-std-stable-2024-02-08/lib/rustlib/aarch64-apple-darwin/lib/libcore-62a9b4d83244cb2b.rlib" "/nix/store/mjgy0lbj4gym3w40g28ijkgsfa5l7wiv-rust-std-stable-2024-02-08/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-4010f8e9d1f7f9aa.rlib" "-framework" "CoreFoundation" "-framework" "CoreFoundation" "-framework" "CoreServices" "-liconv" "-lSystem" "-lc" "-lm" "-L" "/nix/store/idppma96mlgcsfkdka14ln7kanr805dq-clippy-stable-with-std-2024-02-08/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/maximilian/workspace/prql/target/debug/deps/prqlc-a1c56f07e7ba5463" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: ld: framework not found CoreServices
          clang-11: error: linker command failed with exit code 1 (use -v to see invocation)

```

```
$ cc --version
clang version 11.1.0
Target: aarch64-apple-darwin
Thread model: posix
InstalledDir: /nix/store/gcbmg7a0fhdcda42g7qp7ngqcix7bax5-clang-11.1.0/bin
```

---

Surely we can't be the first people to try build stuff like this on Nix & Mac?! 

I was a bit skeptical of Nix, even though I love the vision, so don't work on this as any favor to me... 
Possibly we leave it for a while and come back in the ecosystem improves? Would be great to be able to test on GHA at least...

**Comment by aljazerzen** [comment]
Well, we do have an advanced use-case where need a bunch of build-time and run-time dependencies for many language bindings.

But yeah - not the best start. Maybe it has to do with my home-backed flake.nix engineering...

**Comment by max-sixty** [comment]
> Well, we do have an advanced use-case where need a bunch of build-time and run-time dependencies for many language bindings.

Totally, this is indeed the dream!

For the moment, installing peripheral dependencies — i.e. less used bindings — with the taskfile, or in some cases manually isn't _too_ bad. And GHA offers a slow-but-reliable iteration cycle. I'm doing that in #4241, it's OK!

**Comment by aljazerzen** [comment]
Ok, let's leave it as is for now.

I'll merge this PR, because it does contain useful stuff for me too.

**Pull request merged**
