### PR TITLE
docs: Introducing PRQL Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [PRQL Guru](https://gurubase.io/g/prql) to Gurubase. PRQL Guru uses the data from this repo and data from the [docs](https://prql-lang.org/book) to answer questions by leveraging the LLM.

In this PR, I showcased the "PRQL Guru", which highlights that PRQL now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable PRQL Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Comment by vanillajonathan** [comment]
Hi and thank you for adding PRQL to Gurubase!

I quickly tried it out and it seems very nice! I like it!

**Comment by max-sixty** [comment]
Hi @kursataktas

Gurubase looks cool! Congrats on building it. I'm happy to add a link somewhere from our docs. That initial section on the Readme is designed for things people are already looking for, though, so isn't a good location.

Does anyone have ideas for where else we could link from? Somewhere in the Book? (I can't immediately see where though...)

**Comment by richb-hanover** [comment]
@kursataktas PRQL Guru is quite interesting. I like that gives a detailed explanation with sample code with a "Copy" button (all of which I've grown used to) and that it lists Sources at the bottom.

What's the best place to report surprising results? For example, "give me a PRQL query that finds all the rows in table1 that don't exist in table2. Use the foo column to match the rows." 

It responds with:

```
 from table1
remove table2 (==foo)
```
PS: When I ask PRQL Guru whether `remove` is a transform, it says no... 
PPS: BUT... when I check the Sources and click on "Apend" (a typo), the PRQL documentation lists `remove` as _experimental_...

**Comment by richb-hanover** [comment]
@max-sixty 
> Does anyone have ideas for where else we could link from? Somewhere in the Book? (I can't immediately see where though...)

Having just updated the [qStudio](https://prql-lang.org/book/project/integrations/qstudio.html) page in the Book, I imagine there could be a similar page in the Integrations section.

**Comment by kursataktas** [comment]
Hi @max-sixty ,
Thanks for the review. I can definitely add a link to the docs if you can guide me on the best place to put it. Alternatively, what do you think about adding a widget like the one we use on [Anteon Docs](https://getanteon.com/docs/#-kubernetes-monitoring)?
Screenshot 2024-11-07 at 23 09 04

**Comment by kursataktas** [comment]
> @kursataktas PRQL Guru is quite interesting. I like that gives a detailed explanation with sample code with a "Copy" button (all of which I've grown used to) and that it lists Sources at the bottom.
> 
> What's the best place to report surprising results? For example, "give me a PRQL query that finds all the rows in table1 that don't exist in table2. Use the foo column to match the rows."
> 
> It responds with:
> 
> ```
>  from table1
> remove table2 (==foo)
> ```
> 
> PS: When I ask PRQL Guru whether `remove` is a transform, it says no... PPS: BUT... when I check the Sources and click on "Apend" (a typo), the PRQL documentation lists `remove` as _experimental_...

Thanks for the review, @richb-hanover.
 I'm continuously working on improving the accuracy of the generated answers.  Reports like these are very helpful. 

These are the ones you mentioned, right?
 - https://gurubase.io/g/prql/prql-query-find-rows-in-table1-not-in-table2
 - https://gurubase.io/g/prql/is-remove-a-transform-in-prql
 
 For future issue reports, our [Discord channel](https://discord.gg/9CMRSQPqx6) is the best place to communicate.

**Comment by kursataktas** [comment]
@richb-hanover 
Have you had a chance to look into my latest reply?

Additionally, I’d like to update you on the release of the Maintainer Panel feature on Gurubase. With this panel, you can add, remove, or update data sources, as well as change the logo and more. You can find the details [here](https://github.com/getanteon/gurubase?tab=readme-ov-file#how-to-claim-a-guru). 

In the near future, I’m planning to include analytics insights in this panel, such as the number of questions asked, the most frequently asked ones, and more. I’ll be sure to update this thread once it’s available. However, in case I miss it, I highly recommend joining our [Discord channel](https://discord.gg/9CMRSQPqx6) to stay updated.

If you’d prefer that I don’t update this thread anymore, please let me know.

**Comment by max-sixty** [comment]
Just catching up on this thread, sorry for the delay.

I'm a fan in spirit of tools like Gurubase. But I don't see a great place to put a link and — similar to our response at xarray — I also am a bit wary of boosting a solution which is "cool but not perfect", particularly given there are lots of competing tools.

When there's something that people are already using, then happy to add something.

(thinking about my response here — I should have written this initially, would have saved others some time...)

**Pull request closed without merging**
