### PR TITLE
feat: indirection parsing

### PR DESCRIPTION
**Pull request by aljazerzen**
Parsing for these:
```
"hello".length
{a = 1}.1
123.length
```

### CODE REVIEW

**Comment by vanillajonathan** [comment]
Seems really cool!

I brought up a discussion earlier in #1767 which sounds related.

**Comment by max-sixty** [comment]
Is the intention that in `foo.bar`, `bar` can be a function which takes `foo` as an input?

If so, how would we discriminate between the column `bar` and a function `bar` in `foo.bar`?

**Comment by aljazerzen** [comment]
No, i didnt mean to use this for associated functions/methods - i mean to use it for accessing fields of a tuple.

**Comment by max-sixty** [comment]
OK yes great. So then are the top and bottom examples right?

> "hello".length
> {a = 1}.1
> 123.length

**Comment by aljazerzen** [comment]
Syntactically, yes. Semantically, no.

**Comment by max-sixty** [comment]
Cool, thanks

**Pull request merged**
