### PR TITLE
ci: Add back normal `docker compose`

### PR DESCRIPTION
**Pull request by max-sixty**
Runners have been upgraded

### CODE REVIEW

**Review by eitsupi — CHANGES_REQUESTED** [review]
It contains unnecessary changes; removing L62-66 should be sufficient.

**Comment by eitsupi** [comment]
ref: actions/runner-images#7686

**Comment by eitsupi** [comment]
So it seems that this was not an upgrade but a revert to the previous version.

**Comment by max-sixty** [comment]
@eitsupi you've auto-merged but also blocked on changes! 😁 😁 

Shall I add back L60?

**Review by eitsupi — APPROVED** [review]

**Comment by eitsupi** [comment]
> @eitsupi you've auto-merged but also blocked on changes! 😁 😁
> 
> Shall I add back L60?

Sorry!

We ought to be able to forget about that.

**Comment by max-sixty** [comment]
Thanks!

**Pull request merged**
