### PR TITLE
docs: Write down naming approach

### PR DESCRIPTION
**Pull request by max-sixty**
As discussed in https://discord.com/channels/936728116712316989/1195504018882035752

Do we all agree?

### CODE REVIEW

**Review by aljazerzen — COMMENTED** [review]
Beautiful :D

**Comment by eitsupi** [comment]
I think this is a good approach, but as I think I've commented somewhere before, please note that changing prqlr to prqlc from now on is not allowed by CRAN so I can't change it.

**Comment by max-sixty** [comment]
> I think this is a good approach, but as I think I've commented somewhere before, please note that changing prqlr to prqlc from now on is not allowed by CRAN so I can't change it.

OK, I can add.

Would we ever want to start a new package `prqlc`? (Or that's also not allowed)

@eitsupi FWIW I was less keen on making lots of changes, but I can see the benefit of unifying things. So from my perspective no rush or pressure to change the external interfaces...

**Comment by eitsupi** [comment]
> Would we ever want to start a new package `prqlc`? (Or that's also not allowed)

Of course it is possible, but it would mean having to maintain two parallel GitHub repositories and switching between them.
It would make sense if, for example, this was close to version 1.0.0, etc, I don't want to do that at the moment because it would be too much trouble.

**Comment by eitsupi** [comment]
Perhaps the most practical way is to publish the current prqlr as a new prqlc and publish a new version of the prqlr package that just re-exports prqlc.
https://stackoverflow.com/questions/22654421/how-to-rename-an-existing-r-package-on-cran

**Comment by max-sixty** [comment]
> Perhaps the most practical way is to publish the current prqlr as a new prqlc and publish a new version of the prqlr package that just re-exports prqlc.
> https://stackoverflow.com/questions/22654421/how-to-rename-an-existing-r-package-on-cran

Yes, that's what we do for `prql-compiler` now.

---

TBC, no rush for these. The owner ultimately decides, so up to you on what we do with `prqlr`

**Comment by eitsupi** [comment]
Of course, I am not sure if that is actually done. Aside from changing the package, changing the repository could invalidate the URLs referenced from CRAN, so at worst the package will be removed from CRAN in the process of being worked on.

**Pull request merged**
