### PR TITLE
docs: Clarify s-string changelog

### PR DESCRIPTION
**Pull request by max-sixty**

### CODE REVIEW

**Comment by aljazerzen** [comment]
How are you creating so much PRs so fast?

**Comment by max-sixty** [comment]
> How are you creating so much PRs so fast?

Unsurprisingly perhaps — not because I'm actually fast! Instead, I can create & merge a PR with three characters...

---

I have a three character alias `gpm` for `git pub-merge`, in `fish`:

```fish
  abbr -a --global -- gpm git pub-merge
```

And `git pub-merge` publishes the branch and opens a PR, marking it to auto-merge. Git config:

```
[alias]
    pub-merge      = "!if git remote -v | rg github > /dev/null; then git pub-merge-gh; elif git remote -v | rg gitlab > /dev/null; then git pub-merge-gl; else exit 1; fi"
    pub-merge-gh   = !git publish && gh pr create --fill && gh pr merge --auto --squash --delete-branch
    publish        = "!git push --set-upstream origin $(git branch --show-current)"
```

(others can ignore the github / gitlab distinction and just use the code in `pub-merge-gh`:

---

And if I'm already on a branch, I also have `gwp` alias to `git commit-wip; git publish`, so I can commit & push any changes very quickly. The commit will be squashed away on merge, so it doesn't matter about the message.

```
  abbr -a --global -- gwp "git commit-wip; git publish"
```

```
[alias]
    commit-all     = "!git add -A && git commit"
    commit-wip     = commit-all --allow-empty-message -m ""
```

**Comment by aljazerzen** [comment]
Ahhhh, I knew that so many small PRs needed some kind of better tooling. Don't mind if I adopt some of them :D

**Comment by aljazerzen** [comment]
Here is the most useful of mine:
```
alias gg="git log --branches --remotes --tags --graph --pretty='%C(yellow)%h %C(cyan)%cd %Cblue%aN%C(auto)%d %Creset%s' --date=relative"
```

It produces this:
```
* 5f6c5a9 3 days ago Maximilian Roos docs: Add docs re consistent ordering (#1381)
* d2ad519 3 days ago Maximilian Roos chore: Add markdownlint exception (#1386)
| * 466cf1b 2 days ago Aljaž Mur Eržen (max/roadmap, roadmap) an empty commit
| * 0b9f80b 2 days ago Aljaž Mur Eržen issues breakdown
| * 4a75ea7 2 days ago Aljaž Mur Eržen fix typos, expand paragraphs
| *   ddeeb41 3 days ago Maximilian Roos Merge branch 'main' into roadmap
| |\
| * | 816bb5f 3 days ago Maximilian Roos .
| * |   aa33aaf 4 days ago Maximilian Roos Merge branch 'main' into roadmap
| |\ \
| * | | b0e83d9 4 days ago Maximilian Roos docs: [draft] Update roadmap
| | | | * 39e7f47 3 days ago Aljaž Mur Eržen (error-msg) refactor
| | | | * aa85561 3 days ago JettChenT doc: Better error message for missing args (#1171)
| |_|_|/
|/| | |
* | | | 18741ba 3 days ago Maximilian Roos build: Replace python pre-commit tools with ruff (#1383)
| |_|/
|/| |
* | | bf1a2ad 4 days ago Maximilian Roos build: Add a `run-web` task (#1382)
| |/
|/|
* | a4de4ca 4 days ago Maximilian Roos (max/main) docs: Clarify note re using aliases in book (#1373)
* | 8bb575d 4 days ago Maximilian Roos test: Add task for watching unit tests (#1380)
* | 1e19f3c 4 days ago Maximilian Roos docs: Sort can accept expressions (#1379)
* | e07b3c4 4 days ago hbc docs: remove redundant word (#1375)
* | 44db34d 4 days ago Sekhar Ravinutala docs: fix website link for dialects (#1377)
|/
* db1de89 4 days ago Maximilian Roos docs: Remove footer from generated SQL in book (#1371)
* fe30f31 4 days ago Maximilian Roos docs: Make s-strings more prominent in the book (#1370)
* eedc7fa 5 days ago Aljaž Mur Eržen docs: static tweets for website (#1366)
* d555bb2 5 days ago dependabot[bot] chore: bump once_cell from 1.16.0 to 1.17.0 (#1368)
* ecc8bd4 5 days ago Aljaž Mur Eržen fix: tweak website code css (#1365)
```

**Pull request merged**
