### PR TITLE
ci: Consolidate check-links-book into pull-request.yaml

### PR DESCRIPTION
**Pull request by max-sixty**
Stacked on https://github.com/PRQL/prql/pull/3182

### CODE REVIEW

**Comment by not-my-profile** [comment]
What's the reasoning for this change?

**Comment by max-sixty** [comment]
> What's the reasoning for this change?

Less indirection — is there a reason to have them separate if the child is only called from a single parent?

**Comment by max-sixty** [comment]
I hadn't realized it at the time, but I guess it'll also solve the issue in https://github.com/PRQL/prql/pull/3185 re too many workflows

**Review by eitsupi — APPROVED** [review]
I think it makes sense and I want to merge this to fix https://github.com/PRQL/prql/pull/3185#issuecomment-1658345218

**Pull request merged**
