### PR TITLE
ci: Fix failing Snap build

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Comment by max-sixty** [comment]
Thanks @vanillajonathan !

**Comment by vanillajonathan** [comment]
Can you get 0.9.4 out on the Snap store?

**Comment by max-sixty** [comment]
I actually not sure that's easy to do, since working code to release in not in the place as the rust code for 0.9.4. If we've had issues with something like `prql-js`, I've released locally or done another release.

Are we OK to wait until 0.9.5? The changes are small from 0.9.3...

**Comment by vanillajonathan** [comment]
Sure, the reason I wanted it published is to download it from Snap and verify that the core22 works as expected, so that I can go ahead and create a new PR that changes the `grade` property from `devel` to `stable`.

**Comment by max-sixty** [comment]
Can we run a dry-run? That won't let you download it, but it might test that it's working. We now have a good system for testing publishing in the workflow, by setting it to only actually publish when the `publish` input is true...

**Comment by vanillajonathan** [comment]
We can wait, I want to download it from the Snap store anyway.

**Pull request merged**
