### PR TITLE
ci: build release artifacts nightly

### PR DESCRIPTION
**Pull request by eitsupi**
ref #2639, PRQL/pyprql#209

Set up nightly builds of prqlc and prql-python wheels to be the same as at the time of release.
Doing this with every push was clearly excessive.

### CODE REVIEW

**Review by max-sixty — APPROVED** [review]
Great! Thank you!

>  Doing this with every push was clearly excessive.

Should we reduce this, then? I don't think this PR changes the prqlc build on PRs.

FWIW — I originally thought it was a bit excessive, but also appreciate your perspective and am happy to have it run frequently if you / others use them.

(We could also add them to `test-all.yaml`, then they run on each merge, or on request, if someone wants to try out `prqlc`. I leave the decision to you!)

**Comment by eitsupi** [comment]
Thanks for your review!

> I don't think this PR changes the prqlc build on PRs.

I mean #2778 already changed that.

**Comment by eitsupi** [comment]
> (We could also add them to `test-all.yaml`, then they run on each merge, or on request, if someone wants to try out `prqlc`. I leave the decision to you!)

My concern is these are numerous and take a long time to build, as you say, so every time I run it, we have to wait quite a bit if we are creating multiple PRs at the same time.

If we want to try a release build we can use the `pr-nightly` tag...... (great design!)

**Comment by max-sixty** [comment]
> I mean #2778 already changed that.

Ah great, I see what you mean by `release` — yes this is a great balance — we get the fast debug builds, but also the tests for `release` before we do the actual releases!

**Comment by eitsupi** [comment]
But thinking about it again, it may be better to call `release.yaml` using `workflow_call` than to copy the contents.

**Pull request merged**
