### PR TITLE
docs: Split DEVELOPMENT.md from CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by richb-hanover**
I felt the urge to separate the community-building aspect from the CONTRIBUTING.md document from the "how to develop" information there. 

I also thought it was important that the new DEVELOPMENT.md file point a newcomer to the various components of the PRQL project, and where to find information about how to work with them.

I'm not sure I have got the split between these documents entirely correct. Feel free to move information between them. Thanks.

### CODE REVIEW

**Comment by max-sixty** [comment]
This looks very reasonable, thanks for contributing @richb-hanover . I admittedly wasn't familiar with `DEVELOPING.md`, but some light Googling suggests it's fairly standard — e.g. https://github.com/github/docs/blob/main/contributing/development.md.

Did you intend to bump the playground dependencies?

**Comment by richb-hanover** [comment]
> Did you intend to bump the playground dependencies?

Yes, I moved them up to the current versions, according to npmjs.com. I was trying to evade the deprecation warnings from `npm install`. 

But no dice: I still see warnings for `stable@0.1.8:` and `svgo@1.3.2` that seem to get pulled in from `@svgr/plugin-svgo@5.5.0` that gets pulled in from `@svgr/webpack@5.5.0` which itself is a dependency of `wasm-react-scripts@5.0.3` 

Thanks.

**Comment by max-sixty** [comment]
~Could we split that out~

> But no dice: I still see warnings for `stable@0.1.8:` and `svgo@1.3.2` that seem to get pulled in from `@svgr/plugin-svgo@5.5.0` that gets pulled in from `@svgr/webpack@5.5.0` which itself is a dependency of `wasm-react-scripts@5.0.3`

😬 

Thanks for trying though!

**Comment by max-sixty** [comment]
Cheers @richb-hanover — great to have you as a contributor!

**Comment by richb-hanover** [comment]
@max-sixty  Did some research... There's a long-standing pull request to update the dependencies of `wasm-react-scripts`. The interesting conversation is at: https://github.com/facebook/create-react-app/pull/12172#issuecomment-1232973824

**Pull request merged**
