### PR TITLE
docs: Add FAQ re capitalization

### PR DESCRIPTION
**Pull request by max-sixty**
The important questions!

Do folks this is a good idea? Or we could do lowercase for everything?

### CODE REVIEW

**Comment by aljazerzen** [comment]
It's an abbreviation - so it should be uppercase, right?

**Comment by max-sixty** [comment]
Yes, fair point. But then should we rename everything to the uppercase? e.g. this repo? Or we say repos are generally lowercase but we use uppercase in all prose?

**Comment by aljazerzen** [comment]
Yes, exactly. We just use kebab-casing for naming repos and crates, but it's uppercase actually.

**Comment by max-sixty** [comment]
OK, I'm fine with that — I'll make the change unless anyone else has a view

**Comment by max-sixty** [comment]
And are we OK to rename the organization to `PRQL` so this repo is `PRQL/prql`?

**Comment by snth** [comment]
I'm happy with the proposal to rename the organisation to `PRQL`.

**Comment by aljazerzen** [comment]
Go ahead with rename and merge of this.

**Comment by max-sixty** [comment]
I changed the org name, I'll update the PR and do some more renames (unless anyone gets there first, but not expecting anyone to)

**Pull request merged**
