### PR TITLE
web: Add Vite to playground

### PR DESCRIPTION
**Pull request by vanillajonathan**
@richb-hanover in #3459 wanted Vite on the playground. He can have it!

### CODE REVIEW

**Comment by max-sixty** [comment]
Awesome!

Does this let us remove `wasm-react-scripts`?

**Comment by vanillajonathan** [comment]
> Does this let us remove `wasm-react-scripts`?

Yes, because now we rely on [`vite-plugin-wasm`](https://github.com/Menci/vite-plugin-wasm) instead.

Hmm, do you know anything about this mdbook-admonish thing? Can you fix it?

**Comment by max-sixty** [comment]
> Hmm, do you know anything about this mdbook-admonish thing? Can you fix it?

Yes, on it!

**Comment by max-sixty** [comment]
> Yes, because now we rely on [`vite-plugin-wasm`](https://github.com/Menci/vite-plugin-wasm) instead.

Awesome!

**Comment by max-sixty** [comment]
@vanillajonathan could you try merging `main` into this? 

(alternatively tick this box and then I can...)

image

**Comment by vanillajonathan** [comment]
@max-sixty okay!

**Comment by max-sixty** [comment]
It looks like it almost completes successfully, but is failing at rsync — worth taking a look and ensuring it can run all the way through.

(Also sorry but a dependency upgrade auto-merged, so you'll have to merge the `package.json`s and then recreate the `package-lock.json`)

Happy to help with either if you get stuck, thanks!

**Comment by vanillajonathan** [comment]
> It looks like it almost completes successfully, but is failing at rsync — worth taking a look and ensuring it can run all the way through.

I fixed this in the `Taskfile.yml`. The issue occurred because Vite outputs to `dist/` instead of `build/`.

> 
> (Also sorry but a dependency upgrade auto-merged, so you'll have to merge the `package.json`s and then recreate the `package-lock.json`)
> 
> Happy to help with either if you get stuck, thanks!

My `package.json` also have the new Monaco update. I generated a new `package-lock.json` file but there is still a conflict that I could need some help with.

**Comment by max-sixty** [comment]
> My `package.json` also have the new Monaco update. I generated a new `package-lock.json` file but there is still a conflict that I could need some help with.

Great, done! I regenerated the `package-lock.json` file...

**Comment by richb-hanover** [comment]
This is great news! I'm traveling now, but will check this out when I return this weekend. Thanks!

**Comment by max-sixty** [comment]
Many thanks @vanillajonathan ! This is a great upgrade to the build.

Sorry I let it linger for a few days at the end. Always feel free to @ me if something is waiting on me.

**Comment by max-sixty** [comment]
And for clarity — this clears up our dependencies; we're no longer relying on dozens of deprecated packages. And it makes it a bit faster.

But much of the time is spent in `wasm-opt`, so it can't take the total build time down beyond that. (For that we'd need https://github.com/PRQL/prql/pull/2907)

**Comment by richb-hanover** [comment]
@vanillajonathan This is a terrific enhancement. Thanks. See #3709 for some fussy comments.

**Pull request merged**
