### PR TITLE
fix: pow for mssql

### PR DESCRIPTION
**Pull request by PrettyWood**
https://github.com/PRQL/prql/pull/3909#discussion_r1421830722

### CODE REVIEW

**Review by max-sixty — APPROVED** [review]
Great, thanks!

**Comment by max-sixty** [comment]
FYI I spent an hour trying to get right-associative to work in the parser. I didn't manage; I can resume. It's not easy!

**Comment by PrettyWood** [comment]
Hmmm... I reckon it's not worth spending too much time on it right now

**Comment by max-sixty** [comment]
For getting right-associative to work, I think we should probably wait for Chumsky 1.0. (tracker at https://github.com/zesterer/chumsky/issues/543)

It implements a Pratt parser — https://github.com/zesterer/chumsky/issues/145 & https://github.com/zesterer/chumsky/pull/464.

We could alternatively write something customized (https://github.com/01mf02/jaq/blob/c79f8b210036a7c15da7a7c8b436e2430ca22338/jaq-parse/src/prec_climb.rs), but if it becomes obsolete, maybe not worthwhile...

**Pull request merged**
