### PR TITLE
fix: generate `FALSE` instead of `expr in ()` conditions

### PR DESCRIPTION
**Pull request by Globidev**
This is an attempt at fixing #4595

Disclaimer: Pretty fluent in Rust but I just discovered the codebase, so I probably missed a bunch of things. 
I guess we'll want to add tests, and I'll likely need some directions as to where exactly to put them :)

### CODE REVIEW

**Comment by max-sixty** [comment]
Awesome @Globidev ! Nice work.

We can add a test next to https://github.com/PRQL/prql/blob/6b4c4389cff35b04296f234e5639cd45be401087/prqlc/prqlc/tests/integration/sql.rs#L1213-L1226

Then running `cargo insta test --accept` (or `task test-rust`) will fill in the generated SQL.

**Comment by max-sixty** [comment]
A changelog entry would be nice but not strictly required

**Comment by Globidev** [comment]
Thanks a bunch for the pointers!

Feel free to point out anything that would be missing or need tweaking

**Comment by max-sixty** [comment]
Super, thanks @Globidev !

**Pull request merged**
