### PR TITLE
Correct reference link in Playground

### PR DESCRIPTION
**Pull request by StevenMaude**

### CODE REVIEW

**Comment by StevenMaude** [comment]
I took it that the intent was to point to the Language Book; hope that's right! :crossed_fingers:

**Comment by max-sixty** [comment]
Thanks a lot @StevenMaude !

**Comment by StevenMaude** [comment]
Woah, that was quick :zap::grin:

P.S. nice work on your landing page and docs!

**Comment by max-sixty** [comment]
I realize our [markdown-link-check](https://github.com/tcort/markdown-link-check) doesn't check the html. Not sure if there's anything we can do to prevent this; though I guess we don't have _that_ many links in HTML.

**Comment by max-sixty** [comment]
Possibly https://github.com/marketplace/actions/broken-link-check...

**Comment by max-sixty** [comment]
> Woah, that was quick ⚡😁

Thanks — and it's already live: https://prql-lang.org/playground/

**Pull request merged**
